package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppAuditFileTblAudit generated by hbm2java
 */
@Entity
@Table(name = "app_audit_file_tbl_audit")
public class AppAuditFileAuditEntity implements java.io.Serializable {

	private int appAuditFileTblAuditId;
	private String operation;
	private Date processDate;
	private int appAuditFileId;
	private String fileName;
	private byte[] fileContent;
	private String status;
	private Integer auditId;
	private String createdBy;
	private Date createdTs;

	public AppAuditFileAuditEntity() {
	}

	public AppAuditFileAuditEntity(int appAuditFileTblAuditId, int appAuditFileId) {
		this.appAuditFileTblAuditId = appAuditFileTblAuditId;
		this.appAuditFileId = appAuditFileId;
	}

	public AppAuditFileAuditEntity(int appAuditFileTblAuditId, String operation, Date processDate, int appAuditFileId,
			String fileName, byte[] fileContent, String status, Integer auditId, String createdBy, Date createdTs) {
		this.appAuditFileTblAuditId = appAuditFileTblAuditId;
		this.operation = operation;
		this.processDate = processDate;
		this.appAuditFileId = appAuditFileId;
		this.fileName = fileName;
		this.fileContent = fileContent;
		this.status = status;
		this.auditId = auditId;
		this.createdBy = createdBy;
		this.createdTs = createdTs;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "app_audit_file_tbl_audit_id", unique = true, nullable = false)
	public int getAppAuditFileTblAuditId() {
		return this.appAuditFileTblAuditId;
	}

	public void setAppAuditFileTblAuditId(int appAuditFileTblAuditId) {
		this.appAuditFileTblAuditId = appAuditFileTblAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "app_audit_file_id", nullable = false)
	public int getAppAuditFileId() {
		return this.appAuditFileId;
	}

	public void setAppAuditFileId(int appAuditFileId) {
		this.appAuditFileId = appAuditFileId;
	}

	@Column(name = "file_name", length = 100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_content")
	public byte[] getFileContent() {
		return this.fileContent;
	}

	public void setFileContent(byte[] fileContent) {
		this.fileContent = fileContent;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "AUDIT_ID")
	public Integer getAuditId() {
		return this.auditId;
	}

	public void setAuditId(Integer auditId) {
		this.auditId = auditId;
	}

	@Column(name = "CREATED_BY", length = 200)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

}
