package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppBusinessAnalystTblAudit generated by hbm2java
 */
@Entity
@Table(name = "app_business_analyst_tbl_audit")
public class AppBusinessAnalystAuditEntity implements java.io.Serializable {

	private Integer appBusinessAnalystTblAuditId;
	private String operation;
	private Date processDate;
	private int appBusinessAnalyst;
	private Integer businessAnalystId;
	private Integer applicationId;
	private String activityFlag;

	public AppBusinessAnalystAuditEntity() {
	}

	public AppBusinessAnalystAuditEntity(int appBusinessAnalyst) {
		this.appBusinessAnalyst = appBusinessAnalyst;
	}

	public AppBusinessAnalystAuditEntity(String operation, Date processDate, int appBusinessAnalyst,
			Integer businessAnalystId, Integer applicationId, String activityFlag) {
		this.operation = operation;
		this.processDate = processDate;
		this.appBusinessAnalyst = appBusinessAnalyst;
		this.businessAnalystId = businessAnalystId;
		this.applicationId = applicationId;
		this.activityFlag = activityFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "app_business_analyst_tbl_audit_id", unique = true, nullable = false)
	public Integer getAppBusinessAnalystTblAuditId() {
		return this.appBusinessAnalystTblAuditId;
	}

	public void setAppBusinessAnalystTblAuditId(Integer appBusinessAnalystTblAuditId) {
		this.appBusinessAnalystTblAuditId = appBusinessAnalystTblAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "APP_BUSINESS_ANALYST", nullable = false)
	public int getAppBusinessAnalyst() {
		return this.appBusinessAnalyst;
	}

	public void setAppBusinessAnalyst(int appBusinessAnalyst) {
		this.appBusinessAnalyst = appBusinessAnalyst;
	}

	@Column(name = "BUSINESS_ANALYST_ID")
	public Integer getBusinessAnalystId() {
		return this.businessAnalystId;
	}

	public void setBusinessAnalystId(Integer businessAnalystId) {
		this.businessAnalystId = businessAnalystId;
	}

	@Column(name = "APPLICATION_ID")
	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "ACTIVITY_FLAG", length = 1)
	public String getActivityFlag() {
		return this.activityFlag;
	}

	public void setActivityFlag(String activityFlag) {
		this.activityFlag = activityFlag;
	}

}
