package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppDevelopersTblAudit generated by hbm2java
 */
@Entity
@Table(name = "app_developers_tbl_audit")
public class AppDevelopersAuditEntity implements java.io.Serializable {

	private Integer appDevelopersTblAuditId;
	private String operation;
	private Date processDate;
	private int appDevelopersid;
	private Integer developer;
	private Integer application;
	private String status;
	private String activityFlag;

	public AppDevelopersAuditEntity() {
	}

	public AppDevelopersAuditEntity(int appDevelopersid) {
		this.appDevelopersid = appDevelopersid;
	}

	public AppDevelopersAuditEntity(String operation, Date processDate, int appDevelopersid, Integer developer,
			Integer application, String status, String activityFlag) {
		this.operation = operation;
		this.processDate = processDate;
		this.appDevelopersid = appDevelopersid;
		this.developer = developer;
		this.application = application;
		this.status = status;
		this.activityFlag = activityFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "app_developers_tbl_audit_id", unique = true, nullable = false)
	public Integer getAppDevelopersTblAuditId() {
		return this.appDevelopersTblAuditId;
	}

	public void setAppDevelopersTblAuditId(Integer appDevelopersTblAuditId) {
		this.appDevelopersTblAuditId = appDevelopersTblAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "APP_DEVELOPERSID", nullable = false)
	public int getAppDevelopersid() {
		return this.appDevelopersid;
	}

	public void setAppDevelopersid(int appDevelopersid) {
		this.appDevelopersid = appDevelopersid;
	}

	@Column(name = "DEVELOPER")
	public Integer getDeveloper() {
		return this.developer;
	}

	public void setDeveloper(Integer developer) {
		this.developer = developer;
	}

	@Column(name = "APPLICATION")
	public Integer getApplication() {
		return this.application;
	}

	public void setApplication(Integer application) {
		this.application = application;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ACTIVITY_FLAG", length = 1)
	public String getActivityFlag() {
		return this.activityFlag;
	}

	public void setActivityFlag(String activityFlag) {
		this.activityFlag = activityFlag;
	}

}
