package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppDbAdminTblAudit generated by hbm2java
 */
@Entity
@Table(name = "app_db_admin_tbl_audit")
public class AppDbAdminAuditEntity implements java.io.Serializable {

	private Integer appDbAdminTblAuditId;
	private String operation;
	private Date processDate;
	private int appDbAdminId;
	private Integer appDbAdmin;
	private Integer application;
	private String activeFlag;

	public AppDbAdminAuditEntity() {
	}

	public AppDbAdminAuditEntity(int appDbAdminId) {
		this.appDbAdminId = appDbAdminId;
	}

	public AppDbAdminAuditEntity(String operation, Date processDate, int appDbAdminId, Integer appDbAdmin,
			Integer application, String activeFlag) {
		this.operation = operation;
		this.processDate = processDate;
		this.appDbAdminId = appDbAdminId;
		this.appDbAdmin = appDbAdmin;
		this.application = application;
		this.activeFlag = activeFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "app_db_admin_tbl_audit_id", unique = true, nullable = false)
	public Integer getAppDbAdminTblAuditId() {
		return this.appDbAdminTblAuditId;
	}

	public void setAppDbAdminTblAuditId(Integer appDbAdminTblAuditId) {
		this.appDbAdminTblAuditId = appDbAdminTblAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "app_db_admin_id", nullable = false)
	public int getAppDbAdminId() {
		return this.appDbAdminId;
	}

	public void setAppDbAdminId(int appDbAdminId) {
		this.appDbAdminId = appDbAdminId;
	}

	@Column(name = "app_db_admin")
	public Integer getAppDbAdmin() {
		return this.appDbAdmin;
	}

	public void setAppDbAdmin(Integer appDbAdmin) {
		this.appDbAdmin = appDbAdmin;
	}

	@Column(name = "APPLICATION")
	public Integer getApplication() {
		return this.application;
	}

	public void setApplication(Integer application) {
		this.application = application;
	}

	@Column(name = "active_flag", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

}
