package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppDataCustodianTblAudit generated by hbm2java
 */
@Entity
@Table(name = "app_data_custodian_tbl_audit")
public class AppDataCustodianAuditEntity implements java.io.Serializable {

	private Integer appDataCustodianTblAuditId;
	private String operation;
	private Date processDate;
	private int appDataCustodianId;
	private Integer appDataCustodian;
	private Integer application;
	private String activeFlag;

	public AppDataCustodianAuditEntity() {
	}

	public AppDataCustodianAuditEntity(int appDataCustodianId) {
		this.appDataCustodianId = appDataCustodianId;
	}

	public AppDataCustodianAuditEntity(String operation, Date processDate, int appDataCustodianId,
			Integer appDataCustodian, Integer application, String activeFlag) {
		this.operation = operation;
		this.processDate = processDate;
		this.appDataCustodianId = appDataCustodianId;
		this.appDataCustodian = appDataCustodian;
		this.application = application;
		this.activeFlag = activeFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "app_data_custodian_tbl_audit_id", unique = true, nullable = false)
	public Integer getAppDataCustodianTblAuditId() {
		return this.appDataCustodianTblAuditId;
	}

	public void setAppDataCustodianTblAuditId(Integer appDataCustodianTblAuditId) {
		this.appDataCustodianTblAuditId = appDataCustodianTblAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "app_data_custodian_id", nullable = false)
	public int getAppDataCustodianId() {
		return this.appDataCustodianId;
	}

	public void setAppDataCustodianId(int appDataCustodianId) {
		this.appDataCustodianId = appDataCustodianId;
	}

	@Column(name = "app_data_custodian")
	public Integer getAppDataCustodian() {
		return this.appDataCustodian;
	}

	public void setAppDataCustodian(Integer appDataCustodian) {
		this.appDataCustodian = appDataCustodian;
	}

	@Column(name = "application")
	public Integer getApplication() {
		return this.application;
	}

	public void setApplication(Integer application) {
		this.application = application;
	}

	@Column(name = "active_flag", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

}
