package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AppDataOwnerTblAudit generated by hbm2java
 */
@Entity
@Table(name = "app_data_owner_tbl_audit")
public class AppDataOwnerAuditEntity implements java.io.Serializable {
	
	private int appDataOwnerAuditId;
	private String operation;
	private Date processDate;
	private int appDataOwnerId;
	private Integer appDataOwner;
	private Integer application;
	private String activeFlag;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "app_data_owner_audit_id", unique = true, nullable = false)
	public int getAppDataOwnerAuditId() {
		return appDataOwnerAuditId;
	}

	public void setAppDataOwnerAuditId(int appDataOwnerAuditId) {
		this.appDataOwnerAuditId = appDataOwnerAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "app_data_owner_id", nullable = false)
	public int getAppDataOwnerId() {
		return this.appDataOwnerId;
	}

	public void setAppDataOwnerId(int appDataOwnerId) {
		this.appDataOwnerId = appDataOwnerId;
	}

	@Column(name = "app_data_owner")
	public Integer getAppDataOwner() {
		return this.appDataOwner;
	}

	public void setAppDataOwner(Integer appDataOwner) {
		this.appDataOwner = appDataOwner;
	}
	
	@Column(name = "application")
	public Integer getApplication() {
		return this.application;
	}

	public void setApplication(Integer application) {
		this.application = application;
	}

	@Column(name = "active_flag", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	
	
}
