package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApplicationServerTblAudit generated by hbm2java
 */
@Entity
@Table(name = "application_server_tbl_audit")
public class ApplicationServerAuditEntity implements java.io.Serializable {

	private Integer applicationServerTblAuditId;
	private String operation;
	private Date processDate;
	private int applicationServerId;
	private Integer applicationId;
	private Integer serverId;
	private String activityFlag;

	public ApplicationServerAuditEntity() {
	}

	public ApplicationServerAuditEntity(int applicationServerId) {
		this.applicationServerId = applicationServerId;
	}

	public ApplicationServerAuditEntity(String operation, Date processDate, int applicationServerId, Integer applicationId,
			Integer serverId, String activityFlag) {
		this.operation = operation;
		this.processDate = processDate;
		this.applicationServerId = applicationServerId;
		this.applicationId = applicationId;
		this.serverId = serverId;
		this.activityFlag = activityFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "application_server_tbl_audit_id", unique = true, nullable = false)
	public Integer getApplicationServerTblAuditId() {
		return this.applicationServerTblAuditId;
	}

	public void setApplicationServerTblAuditId(Integer applicationServerTblAuditId) {
		this.applicationServerTblAuditId = applicationServerTblAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "APPLICATION_SERVER_ID", nullable = false)
	public int getApplicationServerId() {
		return this.applicationServerId;
	}

	public void setApplicationServerId(int applicationServerId) {
		this.applicationServerId = applicationServerId;
	}

	@Column(name = "APPLICATION_ID")
	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "SERVER_ID")
	public Integer getServerId() {
		return this.serverId;
	}

	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}

	@Column(name = "ACTIVITY_FLAG", length = 1)
	public String getActivityFlag() {
		return this.activityFlag;
	}

	public void setActivityFlag(String activityFlag) {
		this.activityFlag = activityFlag;
	}

}
