package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ApplicationTechnologyTbAudit generated by hbm2java
 */
@Entity
@Table(name = "application_technology_tb_audit")
public class ApplicationTechnologyAuditEntity implements java.io.Serializable {
	
	private int applicationTechnologyAuditId;
	private String operation;
	private Date processDate;
	private int applicationTechnologyId;
	private Integer applicationId;
	private Integer technologyId;
	private String activityFlag;


	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "application_technology_audit_id", nullable = false)
	public int getApplicationTechnologyAuditId() {
		return applicationTechnologyAuditId;
	}

	public void setApplicationTechnologyAuditId(int applicationTechnologyAuditId) {
		this.applicationTechnologyAuditId = applicationTechnologyAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "application_technology_id", nullable = false)
	public int getApplicationTechnologyId() {
		return this.applicationTechnologyId;
	}

	public void setApplicationTechnologyId(int applicationTechnologyId) {
		this.applicationTechnologyId = applicationTechnologyId;
	}

	@Column(name = "application_id")
	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "technology_id")
	public Integer getTechnologyId() {
		return this.technologyId;
	}

	public void setTechnologyId(Integer technologyId) {
		this.technologyId = technologyId;
	}

	@Column(name = "ACTIVITY_FLAG", length = 1)
	public String getActivityFlag() {
		return this.activityFlag;
	}

	public void setActivityFlag(String activityFlag) {
		this.activityFlag = activityFlag;
	}

}
