package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApplicationAuditTblAudit generated by hbm2java
 */
@Entity
@Table(name = "application_audit_tbl_audit")
public class ApplicationAuditAuditEntity implements java.io.Serializable {

	private Integer applicationAuditTblAuditId;
	private String operation;
	private Date processDate;
	private int appAuditId;
	private Integer applicationId;
	private Integer auditId;
	private String activityFlag;

	public ApplicationAuditAuditEntity() {
	}

	public ApplicationAuditAuditEntity(int appAuditId) {
		this.appAuditId = appAuditId;
	}

	public ApplicationAuditAuditEntity(String operation, Date processDate, int appAuditId, Integer applicationId,
			Integer auditId, String activityFlag) {
		this.operation = operation;
		this.processDate = processDate;
		this.appAuditId = appAuditId;
		this.applicationId = applicationId;
		this.auditId = auditId;
		this.activityFlag = activityFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "application_audit_tbl_audit_id", unique = true, nullable = false)
	public Integer getApplicationAuditTblAuditId() {
		return this.applicationAuditTblAuditId;
	}

	public void setApplicationAuditTblAuditId(Integer applicationAuditTblAuditId) {
		this.applicationAuditTblAuditId = applicationAuditTblAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "APP_AUDIT_ID", nullable = false)
	public int getAppAuditId() {
		return this.appAuditId;
	}

	public void setAppAuditId(int appAuditId) {
		this.appAuditId = appAuditId;
	}

	@Column(name = "APPLICATION_ID")
	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "AUDIT_ID")
	public Integer getAuditId() {
		return this.auditId;
	}

	public void setAuditId(Integer auditId) {
		this.auditId = auditId;
	}

	@Column(name = "ACTIVITY_FLAG", length = 1)
	public String getActivityFlag() {
		return this.activityFlag;
	}

	public void setActivityFlag(String activityFlag) {
		this.activityFlag = activityFlag;
	}

}
