package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ApplicationTblAudit generated by hbm2java
 */
@Entity
@Table(name = "application_tbl_audit")
public class ApplicationTblAudit implements java.io.Serializable {
	
	private int applicationTblAuditId;
	private String operation;
	private Date processDate;
	private int applicationId;
	private String acronym;
	private String name;
	private Integer officeTblOfficeId;
	private Integer divisionTblDivisionId;
	private Integer updatedBy;
	private Date updatedTs;
	private Integer systemOwner;
	private Integer dataOwner;
	private byte[] description;
	private byte[] technologyStatus;
	private byte[] risks;
	private byte[] consideration;
	private String decisions;
	private Integer approvedBy;
	private Date approvedDate;
	private Integer applicationStatus;
	private String physicalLocation;
	private String systemInterfaces;
	private String systemBoundary;
	private Integer systemSensitivityId;
	private Integer iso;
	private Integer technicalProjectManager;
	private Integer projectManager;
	private Integer systemAdministrator;
	private Integer createdBy;
	private Date createdTs;
	private Integer modifiedBy;
	private Date modifiedTs;
	private Integer businessOwner;
	private Integer dataCustodian;
	private Integer dbAdministrator;
	private String levelOfEffort;
	private String securityAssessments;
	private String boVision1;
	private String boVision2;
	private String boVision3;
	private Integer fiscalYear1;
	private Integer fiscalYear2;
	private Integer fiscalYear3;
	

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "application_tbl_audit_id", nullable = false)
	public int getApplicationTblAuditId() {
		return applicationTblAuditId;
	}

	public void setApplicationTblAuditId(int applicationTblAuditId) {
		this.applicationTblAuditId = applicationTblAuditId;
	}

	@Column(name = "OPERATION", length = 45)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "APPLICATION_ID", nullable = false)
	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "ACRONYM", length = 45)
	public String getAcronym() {
		return this.acronym;
	}

	public void setAcronym(String acronym) {
		this.acronym = acronym;
	}

	@Column(name = "NAME", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "OFFICE_TBL_OFFICE_ID")
	public Integer getOfficeTblOfficeId() {
		return this.officeTblOfficeId;
	}

	public void setOfficeTblOfficeId(Integer officeTblOfficeId) {
		this.officeTblOfficeId = officeTblOfficeId;
	}

	@Column(name = "DIVISION_TBL_DIVISION_ID")
	public Integer getDivisionTblDivisionId() {
		return this.divisionTblDivisionId;
	}

	public void setDivisionTblDivisionId(Integer divisionTblDivisionId) {
		this.divisionTblDivisionId = divisionTblDivisionId;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "UPDATED_TS", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

	@Column(name = "SYSTEM_OWNER")
	public Integer getSystemOwner() {
		return this.systemOwner;
	}

	public void setSystemOwner(Integer systemOwner) {
		this.systemOwner = systemOwner;
	}

	@Column(name = "DATA_OWNER")
	public Integer getDataOwner() {
		return this.dataOwner;
	}

	public void setDataOwner(Integer dataOwner) {
		this.dataOwner = dataOwner;
	}

	@Column(name = "DESCRIPTION")
	public byte[] getDescription() {
		return this.description;
	}

	public void setDescription(byte[] description) {
		this.description = description;
	}

	@Column(name = "TECHNOLOGY_STATUS")
	public byte[] getTechnologyStatus() {
		return this.technologyStatus;
	}

	public void setTechnologyStatus(byte[] technologyStatus) {
		this.technologyStatus = technologyStatus;
	}

	@Column(name = "RISKS")
	public byte[] getRisks() {
		return this.risks;
	}

	public void setRisks(byte[] risks) {
		this.risks = risks;
	}

	@Column(name = "CONSIDERATION")
	public byte[] getConsideration() {
		return this.consideration;
	}

	public void setConsideration(byte[] consideration) {
		this.consideration = consideration;
	}

	@Column(name = "DECISIONS", length = 20000)
	public String getDecisions() {
		return this.decisions;
	}

	public void setDecisions(String decisions) {
		this.decisions = decisions;
	}

	@Column(name = "APPROVED_BY")
	public Integer getApprovedBy() {
		return this.approvedBy;
	}

	public void setApprovedBy(Integer approvedBy) {
		this.approvedBy = approvedBy;
	}

	@Column(name = "APPROVED_DATE", length = 19)
	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	@Column(name = "APPLICATION_STATUS")
	public Integer getApplicationStatus() {
		return this.applicationStatus;
	}

	public void setApplicationStatus(Integer applicationStatus) {
		this.applicationStatus = applicationStatus;
	}

	@Column(name = "PHYSICAL_LOCATION")
	public String getPhysicalLocation() {
		return this.physicalLocation;
	}

	public void setPhysicalLocation(String physicalLocation) {
		this.physicalLocation = physicalLocation;
	}

	@Column(name = "SYSTEM_INTERFACES")
	public String getSystemInterfaces() {
		return this.systemInterfaces;
	}

	public void setSystemInterfaces(String systemInterfaces) {
		this.systemInterfaces = systemInterfaces;
	}

	@Column(name = "SYSTEM_BOUNDARY")
	public String getSystemBoundary() {
		return this.systemBoundary;
	}

	public void setSystemBoundary(String systemBoundary) {
		this.systemBoundary = systemBoundary;
	}

	@Column(name = "SYSTEM_SENSITIVITY_ID")
	public Integer getSystemSensitivityId() {
		return this.systemSensitivityId;
	}

	public void setSystemSensitivityId(Integer systemSensitivityId) {
		this.systemSensitivityId = systemSensitivityId;
	}

	@Column(name = "ISO")
	public Integer getIso() {
		return this.iso;
	}

	public void setIso(Integer iso) {
		this.iso = iso;
	}

	@Column(name = "TECHNICAL_PROJECT_MANAGER")
	public Integer getTechnicalProjectManager() {
		return this.technicalProjectManager;
	}

	public void setTechnicalProjectManager(Integer technicalProjectManager) {
		this.technicalProjectManager = technicalProjectManager;
	}

	@Column(name = "PROJECT_MANAGER")
	public Integer getProjectManager() {
		return this.projectManager;
	}

	public void setProjectManager(Integer projectManager) {
		this.projectManager = projectManager;
	}

	@Column(name = "SYSTEM_ADMINISTRATOR")
	public Integer getSystemAdministrator() {
		return this.systemAdministrator;
	}

	public void setSystemAdministrator(Integer systemAdministrator) {
		this.systemAdministrator = systemAdministrator;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "MODIFIED_BY")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "MODIFIED_TS", length = 19)
	public Date getModifiedTs() {
		return this.modifiedTs;
	}

	public void setModifiedTs(Date modifiedTs) {
		this.modifiedTs = modifiedTs;
	}

	@Column(name = "BUSINESS_OWNER")
	public Integer getBusinessOwner() {
		return this.businessOwner;
	}

	public void setBusinessOwner(Integer businessOwner) {
		this.businessOwner = businessOwner;
	}

	@Column(name = "DATA_CUSTODIAN")
	public Integer getDataCustodian() {
		return this.dataCustodian;
	}

	public void setDataCustodian(Integer dataCustodian) {
		this.dataCustodian = dataCustodian;
	}

	@Column(name = "DB_ADMINISTRATOR")
	public Integer getDbAdministrator() {
		return this.dbAdministrator;
	}

	public void setDbAdministrator(Integer dbAdministrator) {
		this.dbAdministrator = dbAdministrator;
	}
    @Column(name = "LEVEL_OF_EFFORT")
	public String getLevelOfEffort() {
		return levelOfEffort;
	}

	public void setLevelOfEffort(String levelOfEffort) {
		this.levelOfEffort = levelOfEffort;
	}

	@Column(name = "SECURITY_ASSESSMENTS")
	public String getSecurityAssessments() {
		return securityAssessments;
	}

	public void setSecurityAssessments(String securityAssessments) {
		this.securityAssessments = securityAssessments;
	}

	@Column(name = "BO_VISION1")
	public String getBoVision1() {
		return boVision1;
	}

	public void setBoVision1(String boVision1) {
		this.boVision1 = boVision1;
	}
 
	@Column(name = "BO_VISION2")
	public String getBoVision2() {
		return boVision2;
	}

	public void setBoVision2(String boVision2) {
		this.boVision2 = boVision2;
	}

	@Column(name = "BO_VISION3")
	public String getBoVision3() {
		return boVision3;
	}

	public void setBoVision3(String boVision3) {
		this.boVision3 = boVision3;
	}
 
	@Column(name = "FISCAL_YEAR_1")
	public Integer getFiscalYear1() {
		return fiscalYear1;
	}

	public void setFiscalYear1(Integer fiscalYear1) {
		this.fiscalYear1 = fiscalYear1;
	}

	@Column(name = "FISCAL_YEAR_2")
	public Integer getFiscalYear2() {
		return fiscalYear2;
	}

	public void setFiscalYear2(Integer fiscalYear2) {
		this.fiscalYear2 = fiscalYear2;
	}

	@Column(name = "FISCAL_YEAR_3")
	public Integer getFiscalYear3() {
		return fiscalYear3;
	}

	public void setFiscalYear3(Integer fiscalYear3) {
		this.fiscalYear3 = fiscalYear3;
	}
	
}
