package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApplDocTblAudit generated by hbm2java
 */
@Entity
@Table(name = "appl_doc_tbl_audit")
public class ApplDocAuditEntity implements java.io.Serializable {

	private Integer applDocTblAuditId;
	private String operation;
	private Date processDate;
	private int documentId;
	private Integer applicationId;
	private String fileName;
	private byte[] fileContent;
	private String fileType;
	private String workflowDiagramFilename;
	private byte[] workflowDiagramContent;
	private String systemDiagramFilename;
	private byte[] systemDiagramContent;
	private String riskAssessmentFilename;
	private byte[] riskAssessmentContent;
	private String businessImpactFilename;
	private byte[] businessImpactContent;
	private String auditFindingsFilename;
	private byte[] auditFindingsContent;
	private Integer createdBy;
	private Date createdTs;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "appl_doc_tbl_audit_id", unique = true, nullable = false)
	public Integer getApplDocTblAuditId() {
		return this.applDocTblAuditId;
	}

	public void setApplDocTblAuditId(Integer applDocTblAuditId) {
		this.applDocTblAuditId = applDocTblAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "DOCUMENT_ID", nullable = false)
	public int getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(int documentId) {
		this.documentId = documentId;
	}

	@Column(name = "APPLICATION_ID")
	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "FILE_NAME", length = 100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "FILE_CONTENT")
	public byte[] getFileContent() {
		return this.fileContent;
	}

	public void setFileContent(byte[] fileContent) {
		this.fileContent = fileContent;
	}

	@Column(name = "FILE_TYPE", length = 100)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "WORKFLOW_DIAGRAM_FILENAME", length = 100)
	public String getWorkflowDiagramFilename() {
		return this.workflowDiagramFilename;
	}

	public void setWorkflowDiagramFilename(String workflowDiagramFilename) {
		this.workflowDiagramFilename = workflowDiagramFilename;
	}

	@Column(name = "WORKFLOW_DIAGRAM_CONTENT")
	public byte[] getWorkflowDiagramContent() {
		return this.workflowDiagramContent;
	}

	public void setWorkflowDiagramContent(byte[] workflowDiagramContent) {
		this.workflowDiagramContent = workflowDiagramContent;
	}

	@Column(name = "SYSTEM_DIAGRAM_FILENAME", length = 100)
	public String getSystemDiagramFilename() {
		return this.systemDiagramFilename;
	}

	public void setSystemDiagramFilename(String systemDiagramFilename) {
		this.systemDiagramFilename = systemDiagramFilename;
	}

	@Column(name = "SYSTEM_DIAGRAM_CONTENT")
	public byte[] getSystemDiagramContent() {
		return this.systemDiagramContent;
	}

	public void setSystemDiagramContent(byte[] systemDiagramContent) {
		this.systemDiagramContent = systemDiagramContent;
	}

	@Column(name = "RISK_ASSESSMENT_FILENAME", length = 100)
	public String getRiskAssessmentFilename() {
		return this.riskAssessmentFilename;
	}

	public void setRiskAssessmentFilename(String riskAssessmentFilename) {
		this.riskAssessmentFilename = riskAssessmentFilename;
	}

	@Column(name = "RISK_ASSESSMENT_CONTENT")
	public byte[] getRiskAssessmentContent() {
		return this.riskAssessmentContent;
	}

	public void setRiskAssessmentContent(byte[] riskAssessmentContent) {
		this.riskAssessmentContent = riskAssessmentContent;
	}

	@Column(name = "BUSINESS_IMPACT_FILENAME", length = 100)
	public String getBusinessImpactFilename() {
		return this.businessImpactFilename;
	}

	public void setBusinessImpactFilename(String businessImpactFilename) {
		this.businessImpactFilename = businessImpactFilename;
	}

	@Column(name = "BUSINESS_IMPACT_CONTENT")
	public byte[] getBusinessImpactContent() {
		return this.businessImpactContent;
	}

	public void setBusinessImpactContent(byte[] businessImpactContent) {
		this.businessImpactContent = businessImpactContent;
	}

	@Column(name = "AUDIT_FINDINGS_FILENAME", length = 100)
	public String getAuditFindingsFilename() {
		return this.auditFindingsFilename;
	}

	public void setAuditFindingsFilename(String auditFindingsFilename) {
		this.auditFindingsFilename = auditFindingsFilename;
	}

	@Column(name = "AUDIT_FINDINGS_CONTENT")
	public byte[] getAuditFindingsContent() {
		return this.auditFindingsContent;
	}

	public void setAuditFindingsContent(byte[] auditFindingsContent) {
		this.auditFindingsContent = auditFindingsContent;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

}
