package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppProjectManagerTblAudit generated by hbm2java
 */
@Entity
@Table(name = "app_project_manager_tbl_audit")
public class AppProjectManagerAuditEntity implements java.io.Serializable {

	private Integer appProjectManagerTblAuditId;
	private String operation;
	private Date processDate;
	private int appProjectManagerId;
	private Integer appProjectManager;
	private Integer application;
	private String activeFlag;

	public AppProjectManagerAuditEntity() {
	}

	public AppProjectManagerAuditEntity(int appProjectManagerId) {
		this.appProjectManagerId = appProjectManagerId;
	}

	public AppProjectManagerAuditEntity(String operation, Date processDate, int appProjectManagerId,
			Integer appProjectManager, Integer application, String activeFlag) {
		this.operation = operation;
		this.processDate = processDate;
		this.appProjectManagerId = appProjectManagerId;
		this.appProjectManager = appProjectManager;
		this.application = application;
		this.activeFlag = activeFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "app_project_manager_tbl_audit_id", unique = true, nullable = false)
	public Integer getAppProjectManagerTblAuditId() {
		return this.appProjectManagerTblAuditId;
	}

	public void setAppProjectManagerTblAuditId(Integer appProjectManagerTblAuditId) {
		this.appProjectManagerTblAuditId = appProjectManagerTblAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "app_project_manager_id", nullable = false)
	public int getAppProjectManagerId() {
		return this.appProjectManagerId;
	}

	public void setAppProjectManagerId(int appProjectManagerId) {
		this.appProjectManagerId = appProjectManagerId;
	}

	@Column(name = "app_project_manager")
	public Integer getAppProjectManager() {
		return this.appProjectManager;
	}

	public void setAppProjectManager(Integer appProjectManager) {
		this.appProjectManager = appProjectManager;
	}

	@Column(name = "application")
	public Integer getApplication() {
		return this.application;
	}

	public void setApplication(Integer application) {
		this.application = application;
	}

	@Column(name = "active_flag", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

}
