package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AppSystemOwnerTblAudit generated by hbm2java
 */
@Entity
@Table(name = "app_system_owner_tbl_audit")
public class AppSystemOwnerAuditEntity implements java.io.Serializable {
	
	private int appSystemOwnerAuditId;
	private String operation;
	private Date processDate;
	private int appSystemOwnerTblId;
	private Integer appSystemOwner;
	private Integer application;
	private String activeFlag;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "app_system_owner_audit_id", unique = true, nullable = false)
	public int getAppSystemOwnerAuditId() {
		return appSystemOwnerAuditId;
	}

	public void setAppSystemOwnerAuditId(int appSystemOwnerAuditId) {
		this.appSystemOwnerAuditId = appSystemOwnerAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "app_system_owner_tbl_id", nullable = false)
	public int getAppSystemOwnerTblId() {
		return this.appSystemOwnerTblId;
	}

	public void setAppSystemOwnerTblId(int appSystemOwnerTblId) {
		this.appSystemOwnerTblId = appSystemOwnerTblId;
	}

	@Column(name = "app_system_owner")
	public Integer getAppSystemOwner() {
		return this.appSystemOwner;
	}

	public void setAppSystemOwner(Integer appSystemOwner) {
		this.appSystemOwner = appSystemOwner;
	}

	@Column(name = "application")
	public Integer getApplication() {
		return this.application;
	}

	public void setApplication(Integer application) {
		this.application = application;
	}

	@Column(name = "active_flag", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}
}
