package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppSystemAdminTblAudit generated by hbm2java
 */
@Entity
@Table(name = "app_system_admin_tbl_audit")
public class AppSystemAdminAuditEntity implements java.io.Serializable {

	private Integer appSystemAdminTblAuditId;
	private String operation;
	private Date processDate;
	private int appSystemAdminId;
	private Integer appSystemAdmin;
	private Integer application;
	private String activeFlag;

	public AppSystemAdminAuditEntity() {
	}

	public AppSystemAdminAuditEntity(int appSystemAdminId) {
		this.appSystemAdminId = appSystemAdminId;
	}

	public AppSystemAdminAuditEntity(String operation, Date processDate, int appSystemAdminId, Integer appSystemAdmin,
			Integer application, String activeFlag) {
		this.operation = operation;
		this.processDate = processDate;
		this.appSystemAdminId = appSystemAdminId;
		this.appSystemAdmin = appSystemAdmin;
		this.application = application;
		this.activeFlag = activeFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "app_system_admin_tbl_audit_id", unique = true, nullable = false)
	public Integer getAppSystemAdminTblAuditId() {
		return this.appSystemAdminTblAuditId;
	}

	public void setAppSystemAdminTblAuditId(Integer appSystemAdminTblAuditId) {
		this.appSystemAdminTblAuditId = appSystemAdminTblAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "app_system_admin_id", nullable = false)
	public int getAppSystemAdminId() {
		return this.appSystemAdminId;
	}

	public void setAppSystemAdminId(int appSystemAdminId) {
		this.appSystemAdminId = appSystemAdminId;
	}

	@Column(name = "app_system_admin")
	public Integer getAppSystemAdmin() {
		return this.appSystemAdmin;
	}

	public void setAppSystemAdmin(Integer appSystemAdmin) {
		this.appSystemAdmin = appSystemAdmin;
	}

	@Column(name = "application")
	public Integer getApplication() {
		return this.application;
	}

	public void setApplication(Integer application) {
		this.application = application;
	}

	@Column(name = "active_flag", length = 1)
	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

}
