package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppTestersTblAudit generated by hbm2java
 */
@Entity
@Table(name = "app_testers_tbl_audit")
public class AppTestersAuditEntity implements java.io.Serializable {

	private Integer appTestersTblAuditId;
	private String operation;
	private Date processDate;
	private int appTesterId;
	private Integer tester;
	private Integer application;
	private String status;
	private String activityFlag;

	public AppTestersAuditEntity() {
	}

	public AppTestersAuditEntity(int appTesterId) {
		this.appTesterId = appTesterId;
	}

	public AppTestersAuditEntity(String operation, Date processDate, int appTesterId, Integer tester, Integer application,
			String status, String activityFlag) {
		this.operation = operation;
		this.processDate = processDate;
		this.appTesterId = appTesterId;
		this.tester = tester;
		this.application = application;
		this.status = status;
		this.activityFlag = activityFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "app_testers_tbl_audit_id", unique = true, nullable = false)
	public Integer getAppTestersTblAuditId() {
		return this.appTestersTblAuditId;
	}

	public void setAppTestersTblAuditId(Integer appTestersTblAuditId) {
		this.appTestersTblAuditId = appTestersTblAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "APP_TESTER_ID", nullable = false)
	public int getAppTesterId() {
		return this.appTesterId;
	}

	public void setAppTesterId(int appTesterId) {
		this.appTesterId = appTesterId;
	}

	@Column(name = "TESTER")
	public Integer getTester() {
		return this.tester;
	}

	public void setTester(Integer tester) {
		this.tester = tester;
	}

	@Column(name = "APPLICATION")
	public Integer getApplication() {
		return this.application;
	}

	public void setApplication(Integer application) {
		this.application = application;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ACTIVITY_FLAG", length = 1)
	public String getActivityFlag() {
		return this.activityFlag;
	}

	public void setActivityFlag(String activityFlag) {
		this.activityFlag = activityFlag;
	}
	
}
