package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AuditTypeTblAudit generated by hbm2java
 */
@Entity
@Table(name = "audit_type_tbl_audit")
public class AuditTypeAuditEntity implements java.io.Serializable {
	
	private int auditTypeAuditId;
	private String operation;
	private Date processDate;
	private int auditTypeId;
	private String auditName;
	private String createdBy;
	private Date createdTs;
	private String active;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "audit_type_audit_id", unique = true, nullable = false)
	public int getAuditTypeAuditId() {
		return auditTypeAuditId;
	}

	public void setAuditTypeAuditId(int auditTypeAuditId) {
		this.auditTypeAuditId = auditTypeAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "AUDIT_TYPE_ID", nullable = false)
	public int getAuditTypeId() {
		return this.auditTypeId;
	}

	public void setAuditTypeId(int auditTypeId) {
		this.auditTypeId = auditTypeId;
	}

	@Column(name = "AUDIT_NAME", length = 100)
	public String getAuditName() {
		return this.auditName;
	}

	public void setAuditName(String auditName) {
		this.auditName = auditName;
	}

	@Column(name = "CREATED_BY", length = 200)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "ACTIVE", length = 1)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}
	
}
