package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AuditTblAudit generated by hbm2java
 */
@Entity
@Table(name = "audit_tbl_audit")
public class AuditAuditEntity implements java.io.Serializable {
	
	private int auditAuditId;
	private String operation;
	private Date processDate;
	private int auditId;
	private Date lastAudit;
	private Date upcomingAudit;
	private String comments;
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "audit_audit_id", unique = true, nullable = false)
	public int getAuditAuditId() {
		return auditAuditId;
	}

	public void setAuditAuditId(int auditAuditId) {
		this.auditAuditId = auditAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "AUDIT_ID", nullable = false)
	public int getAuditId() {
		return this.auditId;
	}

	public void setAuditId(int auditId) {
		this.auditId = auditId;
	}

	@Column(name = "LAST_AUDIT", length = 19)
	public Date getLastAudit() {
		return this.lastAudit;
	}

	public void setLastAudit(Date lastAudit) {
		this.lastAudit = lastAudit;
	}

	@Column(name = "UPCOMING_AUDIT", length = 19)
	public Date getUpcomingAudit() {
		return this.upcomingAudit;
	}

	public void setUpcomingAudit(Date upcomingAudit) {
		this.upcomingAudit = upcomingAudit;
	}

	@Column(name = "COMMENTS", length = 45)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}
	
	
}
