package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CostTblAudit generated by hbm2java
 */
@Entity
@Table(name = "cost_tbl_audit")
public class CostAuditEntity implements java.io.Serializable {
	
	private int costAuditId;
	private String operation;
	private Date processDate;
	private int costId;
	private String typeNumber;
	private String typeValue;
	private Integer createdBy;
	private Date createdTs;
	private Integer applicationId;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cost_audit_id", unique = true, nullable = false)
	public int getCostAuditId() {
		return costAuditId;
	}

	public void setCostAuditId(int costAuditId) {
		this.costAuditId = costAuditId;
	}
	@Column(name = "operation", length = 19)
	public String getOperation() {
		return operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "COST_ID", nullable = false)
	public int getCostId() {
		return this.costId;
	}

	public void setCostId(int costId) {
		this.costId = costId;
	}

	@Column(name = "TYPE_NUMBER", length = 100)
	public String getTypeNumber() {
		return this.typeNumber;
	}

	public void setTypeNumber(String typeNumber) {
		this.typeNumber = typeNumber;
	}

	@Column(name = "TYPE_VALUE", length = 45)
	public String getTypeValue() {
		return this.typeValue;
	}

	public void setTypeValue(String typeValue) {
		this.typeValue = typeValue;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "APPLICATION_ID")
	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

}
