package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DepartmentTblAudit generated by hbm2java
 */
@Entity
@Table(name = "department_tbl_audit")
public class DepartmentAuditEntity implements java.io.Serializable {
	
	private int departmentAuditId;
	private String operation;
	private Date processDate;
	private int departmentId;
	private String department;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "department_audit_id", unique = true, nullable = false)
	public int getDepartmentAuditId() {
		return departmentAuditId;
	}

	public void setDepartmentAuditId(int departmentAuditId) {
		this.departmentAuditId = departmentAuditId;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "Department_Id", nullable = false)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "Department", length = 45)
	public String getDepartment() {
		return this.department;
	}

}
