package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DivisionTblAudit generated by hbm2java
 */
@Entity
@Table(name = "division_tbl_audit")
public class DivisionAuditEntity implements java.io.Serializable {
	
	private int divisionAuditId;
	private String operation;
	private Date processDate;
	private int divisionId;
	private String divisionName;
	private int officeTblOfficeId;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "division_audit_id", unique = true, nullable = false)
	public int getDivisionAuditId() {
		return divisionAuditId;
	}

	public void setDivisionAuditId(int divisionAuditId) {
		this.divisionAuditId = divisionAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "DIVISION_ID", nullable = false)
	public int getDivisionId() {
		return this.divisionId;
	}

	public void setDivisionId(int divisionId) {
		this.divisionId = divisionId;
	}

	@Column(name = "DIVISION_NAME")
	public String getDivisionName() {
		return this.divisionName;
	}

	public void setDivisionName(String divisionName) {
		this.divisionName = divisionName;
	}

	@Column(name = "OFFICE_TBL_OFFICE_ID", nullable = false)
	public int getOfficeTblOfficeId() {
		return this.officeTblOfficeId;
	}

	public void setOfficeTblOfficeId(int officeTblOfficeId) {
		this.officeTblOfficeId = officeTblOfficeId;
	}

}
