package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FiscalYearInfoTblAudit generated by hbm2java
 */
@Entity
@Table(name = "fiscal_year_info_tbl_audit")
public class FiscalYearInfoAuditEntity implements java.io.Serializable {
	
	private int fiscalYearInfoAuditId;
	private String operation;
	private Date processDate;
	private int fyId;
	private Integer fyNumber;
	private String fyContent;
	private String fyMoaTerm;
	private Integer createdBy;
	private Date createdTs;
	private Integer applicationId;
	private String activityFlag;
	
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "fiscal_year_info_audit_id", unique = true, nullable = false)
	public int getFiscalYearInfoAuditId() {
		return fiscalYearInfoAuditId;
	}

	public void setFiscalYearInfoAuditId(int fiscalYearInfoAuditId) {
		this.fiscalYearInfoAuditId = fiscalYearInfoAuditId;
	}
	@Column(name = "operation")
	public String getOperation() {
		return operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "FY_ID", nullable = false)
	public int getFyId() {
		return this.fyId;
	}

	public void setFyId(int fyId) {
		this.fyId = fyId;
	}

	@Column(name = "FY_NUMBER")
	public Integer getFyNumber() {
		return this.fyNumber;
	}

	public void setFyNumber(Integer fyNumber) {
		this.fyNumber = fyNumber;
	}

	@Column(name = "FY_CONTENT", length = 2000)
	public String getFyContent() {
		return this.fyContent;
	}

	public void setFyContent(String fyContent) {
		this.fyContent = fyContent;
	}

	@Column(name = "FY_MOA_TERM", length = 45)
	public String getFyMoaTerm() {
		return this.fyMoaTerm;
	}

	public void setFyMoaTerm(String fyMoaTerm) {
		this.fyMoaTerm = fyMoaTerm;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "APPLICATION_ID")
	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "ACTIVITY_FLAG", length = 45)
	public String getActivityFlag() {
		return this.activityFlag;
	}

	public void setActivityFlag(String activityFlag) {
		this.activityFlag = activityFlag;
	}
}
