package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MoaTbAudit generated by hbm2java
 */
@Entity
@Table(name = "moa_tb_audit")
public class MoaAuditEntity implements java.io.Serializable {
	
	private int moaAuditId;
	private String operation;
	private Date processDate;
	private int moaId;
	private byte[] moa;
	private String moaName;
	private Date moaSignedDate;
	private Date createdTs;
	private Integer createdBy;
	private Integer applicationId;
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "moa_audit_id", unique = true, nullable = false)
	public int getMoaAuditId() {
		return moaAuditId;
	}

	public void setMoaAuditId(int moaAuditId) {
		this.moaAuditId = moaAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "MOA_ID", nullable = false)
	public int getMoaId() {
		return this.moaId;
	}

	public void setMoaId(int moaId) {
		this.moaId = moaId;
	}

	@Column(name = "MOA")
	public byte[] getMoa() {
		return this.moa;
	}

	public void setMoa(byte[] moa) {
		this.moa = moa;
	}

	@Column(name = "MOA_NAME", length = 100)
	public String getMoaName() {
		return this.moaName;
	}

	public void setMoaName(String moaName) {
		this.moaName = moaName;
	}

	@Column(name = "MOA_SIGNED_DATE", length = 19)
	public Date getMoaSignedDate() {
		return this.moaSignedDate;
	}

	public void setMoaSignedDate(Date moaSignedDate) {
		this.moaSignedDate = moaSignedDate;
	}

	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "APPLICATION_ID")
	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

}
