package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PolicyTblAudit generated by hbm2java
 */
@Entity
@Table(name = "policy_tbl_audit")
public class PolicyAuditEntity implements java.io.Serializable {
	
	private int policyAuditId;
	private String operation;
	private Date processDate;
	private int policyId;
	private String controlNumber;
	private String policyName;
	private String description;
	private String policyVal;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;
	private Integer policyGrpId;
	private String priority;
	private String procudures;
	private String guidelines;
	private String familyName;
	private String familyType;
	private String assignedTo;
	private String assignedBy;
	private Date startDt;
	private Date endDt;
	private String status;
	
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "policy_audit_id", unique = true, nullable = false)
	public int getPolicyAuditId() {
		return policyAuditId;
	}

	public void setPolicyAuditId(int policyAuditId) {
		this.policyAuditId = policyAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "policy_id", nullable = false)
	public int getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(int policyId) {
		this.policyId = policyId;
	}

	@Column(name = "control_number", length = 50)
	public String getControlNumber() {
		return this.controlNumber;
	}

	public void setControlNumber(String controlNumber) {
		this.controlNumber = controlNumber;
	}

	@Column(name = "policy_name", length = 100)
	public String getPolicyName() {
		return this.policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "policy_val", length = 100)
	public String getPolicyVal() {
		return this.policyVal;
	}

	public void setPolicyVal(String policyVal) {
		this.policyVal = policyVal;
	}

	@Column(name = "created_by", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_ts", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "updated_by", length = 100)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "updated_ts", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

	@Column(name = "policy_grp_id")
	public Integer getPolicyGrpId() {
		return this.policyGrpId;
	}

	public void setPolicyGrpId(Integer policyGrpId) {
		this.policyGrpId = policyGrpId;
	}

	@Column(name = "priority", length = 45)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Column(name = "procudures")
	public String getProcudures() {
		return this.procudures;
	}

	public void setProcudures(String procudures) {
		this.procudures = procudures;
	}

	@Column(name = "guidelines")
	public String getGuidelines() {
		return this.guidelines;
	}

	public void setGuidelines(String guidelines) {
		this.guidelines = guidelines;
	}

	@Column(name = "family_name", length = 500)
	public String getFamilyName() {
		return this.familyName;
	}

	public void setFamilyName(String familyName) {
		this.familyName = familyName;
	}

	@Column(name = "family_type", length = 500)
	public String getFamilyType() {
		return this.familyType;
	}

	public void setFamilyType(String familyType) {
		this.familyType = familyType;
	}

	@Column(name = "assigned_to", length = 100)
	public String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

	@Column(name = "assigned_by", length = 100)
	public String getAssignedBy() {
		return this.assignedBy;
	}

	public void setAssignedBy(String assignedBy) {
		this.assignedBy = assignedBy;
	}

	@Column(name = "start_dt", length = 19)
	public Date getStartDt() {
		return this.startDt;
	}

	public void setStartDt(Date startDt) {
		this.startDt = startDt;
	}

	@Column(name = "end_dt", length = 19)
	public Date getEndDt() {
		return this.endDt;
	}

	public void setEndDt(Date endDt) {
		this.endDt = endDt;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
