package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PolicyConfigTblAudit generated by hbm2java
 */
@Entity
@Table(name = "policy_config_tbl_audit")
public class PolicyConfigAuditEntity implements java.io.Serializable {
	
	private int policyConfigAuditId;
	private String operation;
	private Date processDate;
	private int policyConfigId;
	private String policyName;
	private String federal;
	private String state;
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "policy_config_audit_id", unique = true, nullable = false)
	public int getPolicyConfigAuditId() {
		return policyConfigAuditId;
	}

	public void setPolicyConfigAuditId(int policyConfigAuditId) {
		this.policyConfigAuditId = policyConfigAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "POLICY_CONFIG_ID", nullable = false)
	public int getPolicyConfigId() {
		return this.policyConfigId;
	}

	public void setPolicyConfigId(int policyConfigId) {
		this.policyConfigId = policyConfigId;
	}

	@Column(name = "POLICY_NAME", length = 150)
	public String getPolicyName() {
		return this.policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	@Column(name = "FEDERAL", length = 45)
	public String getFederal() {
		return this.federal;
	}

	public void setFederal(String federal) {
		this.federal = federal;
	}

	@Column(name = "STATE", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}
}
