package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PolicySrcNotesTblAudit generated by hbm2java
 */
@Entity
@Table(name = "policy_src_notes_tbl_audit")
public class PolicySrcNotesAuditEntity implements java.io.Serializable {
	
	private int policySrcNotesAuditId;
	private String operation;
	private Date processDate;
	private int policySrcNotesId;
	private String notes;
	private String createdBy;
	private Date createdTs;
	private Integer policyId;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "policy_src_notes_audit_id", unique = true, nullable = false)
	public int getPolicySrcNotesAuditId() {
		return policySrcNotesAuditId;
	}

	public void setPolicySrcNotesAuditId(int policySrcNotesAuditId) {
		this.policySrcNotesAuditId = policySrcNotesAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "POLICY_SRC_NOTES_ID", nullable = false)
	public int getPolicySrcNotesId() {
		return this.policySrcNotesId;
	}

	public void setPolicySrcNotesId(int policySrcNotesId) {
		this.policySrcNotesId = policySrcNotesId;
	}

	@Column(name = "NOTES", length = 500)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "CREATED_BY", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "POLICY_ID")
	public Integer getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}


}
