package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PolicyTypeTblAudit generated by hbm2java
 */
@Entity
@Table(name = "policy_type_tbl_audit")
public class PolicyTypeAuditEntity implements java.io.Serializable {
	
	private int policyTypeAuditId;
	private String operation;
	private Date processDate;
	private int policyTypeId;
	private String typeName;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "policy_type_audit_id", unique = true, nullable = false)
	public int getPolicyTypeAuditId() {
		return policyTypeAuditId;
	}

	public void setPolicyTypeAuditId(int policyTypeAuditId) {
		this.policyTypeAuditId = policyTypeAuditId;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "Policy_type_id", nullable = false)
	public int getPolicyTypeId() {
		return this.policyTypeId;
	}

	public void setPolicyTypeId(int policyTypeId) {
		this.policyTypeId = policyTypeId;
	}

	@Column(name = "Type_name", length = 500)
	public String getTypeName() {
		return this.typeName;
	}

}
