package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReportTblAudit generated by hbm2java
 */
@Entity
@Table(name = "report_tbl_audit")
public class ReportAuditEntity implements java.io.Serializable {
	
	private int reportAuditId;
	private String operation;
	private Date processDate;
	private int formId;
	private String highlightsD;
	private String highlightsC;
	private String criticalIssuesD;
	private String criticalIssuesC;
	private String milestonesD;
	private String milestonesC;
	private String decisionsD;
	private String decisionsC;
	private String goalsD;
	private String goalsC;
	private String otherD;
	private String otherC;
	private Integer departmentId;
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "report_audit_id", unique = true, nullable = false)
	public int getReportAuditId() {
		return reportAuditId;
	}

	public void setReportAuditId(int reportAuditId) {
		this.reportAuditId = reportAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "Form_Id", nullable = false)
	public int getFormId() {
		return this.formId;
	}

	public void setFormId(int formId) {
		this.formId = formId;
	}

	@Column(name = "Highlights_D", length = 1000)
	public String getHighlightsD() {
		return this.highlightsD;
	}

	public void setHighlightsD(String highlightsD) {
		this.highlightsD = highlightsD;
	}

	@Column(name = "Highlights_C", length = 1)
	public String getHighlightsC() {
		return this.highlightsC;
	}

	public void setHighlightsC(String highlightsC) {
		this.highlightsC = highlightsC;
	}

	@Column(name = "CriticalIssues_D", length = 1000)
	public String getCriticalIssuesD() {
		return this.criticalIssuesD;
	}

	public void setCriticalIssuesD(String criticalIssuesD) {
		this.criticalIssuesD = criticalIssuesD;
	}

	@Column(name = "CriticalIssues_C", length = 1)
	public String getCriticalIssuesC() {
		return this.criticalIssuesC;
	}

	public void setCriticalIssuesC(String criticalIssuesC) {
		this.criticalIssuesC = criticalIssuesC;
	}

	@Column(name = "Milestones_D", length = 1000)
	public String getMilestonesD() {
		return this.milestonesD;
	}

	public void setMilestonesD(String milestonesD) {
		this.milestonesD = milestonesD;
	}

	@Column(name = "Milestones_C", length = 1)
	public String getMilestonesC() {
		return this.milestonesC;
	}

	public void setMilestonesC(String milestonesC) {
		this.milestonesC = milestonesC;
	}

	@Column(name = "Decisions_D", length = 1000)
	public String getDecisionsD() {
		return this.decisionsD;
	}

	public void setDecisionsD(String decisionsD) {
		this.decisionsD = decisionsD;
	}

	@Column(name = "Decisions_C", length = 1)
	public String getDecisionsC() {
		return this.decisionsC;
	}

	public void setDecisionsC(String decisionsC) {
		this.decisionsC = decisionsC;
	}

	@Column(name = "Goals_D", length = 1000)
	public String getGoalsD() {
		return this.goalsD;
	}

	public void setGoalsD(String goalsD) {
		this.goalsD = goalsD;
	}

	@Column(name = "Goals_C", length = 1)
	public String getGoalsC() {
		return this.goalsC;
	}

	public void setGoalsC(String goalsC) {
		this.goalsC = goalsC;
	}

	@Column(name = "Other_D", length = 1000)
	public String getOtherD() {
		return this.otherD;
	}

	public void setOtherD(String otherD) {
		this.otherD = otherD;
	}

	@Column(name = "Other_C", length = 1)
	public String getOtherC() {
		return this.otherC;
	}

	public void setOtherC(String otherC) {
		this.otherC = otherC;
	}

	@Column(name = "Department_Id")
	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}


}
