package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * ServerTblAuditId generated by hbm2java
 */
@Embeddable
public class ServerAuditEntity implements java.io.Serializable {
	
	private int serverAuditId;
	private String operation;
	private Date processDate;
	private int serverId;
	private String name;
	private String assetTag;
	private String systemType;
	private String equipmentType;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String zipCode;

	public ServerAuditEntity() {
	}

	public ServerAuditEntity(int serverId) {
		this.serverId = serverId;
	}

	public ServerAuditEntity(String operation, Date processDate, int serverId, String name, String assetTag,
			String systemType, String equipmentType, String addressLine1, String addressLine2, String city,
			String zipCode) {
		this.operation = operation;
		this.processDate = processDate;
		this.serverId = serverId;
		this.name = name;
		this.assetTag = assetTag;
		this.systemType = systemType;
		this.equipmentType = equipmentType;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.zipCode = zipCode;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "report_audit_id", unique = true, nullable = false)
	public int getServerAuditId() {
		return serverAuditId;
	}

	public void setServerAuditId(int serverAuditId) {
		this.serverAuditId = serverAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "SERVER_ID", nullable = false)
	public int getServerId() {
		return this.serverId;
	}

	public void setServerId(int serverId) {
		this.serverId = serverId;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ASSET_TAG", length = 45)
	public String getAssetTag() {
		return this.assetTag;
	}

	public void setAssetTag(String assetTag) {
		this.assetTag = assetTag;
	}

	@Column(name = "SYSTEM_TYPE", length = 45)
	public String getSystemType() {
		return this.systemType;
	}

	public void setSystemType(String systemType) {
		this.systemType = systemType;
	}

	@Column(name = "EQUIPMENT_TYPE", length = 45)
	public String getEquipmentType() {
		return this.equipmentType;
	}

	public void setEquipmentType(String equipmentType) {
		this.equipmentType = equipmentType;
	}

	@Column(name = "ADDRESS_LINE1", length = 100)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE2", length = 100)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "CITY", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ZIP_CODE", length = 20)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServerAuditEntity))
			return false;
		ServerAuditEntity castOther = (ServerAuditEntity) other;

		return ((this.getOperation() == castOther.getOperation()) || (this.getOperation() != null
				&& castOther.getOperation() != null && this.getOperation().equals(castOther.getOperation())))
				&& ((this.getProcessDate() == castOther.getProcessDate())
						|| (this.getProcessDate() != null && castOther.getProcessDate() != null
								&& this.getProcessDate().equals(castOther.getProcessDate())))
				&& (this.getServerId() == castOther.getServerId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getAssetTag() == castOther.getAssetTag()) || (this.getAssetTag() != null
						&& castOther.getAssetTag() != null && this.getAssetTag().equals(castOther.getAssetTag())))
				&& ((this.getSystemType() == castOther.getSystemType()) || (this.getSystemType() != null
						&& castOther.getSystemType() != null && this.getSystemType().equals(castOther.getSystemType())))
				&& ((this.getEquipmentType() == castOther.getEquipmentType())
						|| (this.getEquipmentType() != null && castOther.getEquipmentType() != null
								&& this.getEquipmentType().equals(castOther.getEquipmentType())))
				&& ((this.getAddressLine1() == castOther.getAddressLine1())
						|| (this.getAddressLine1() != null && castOther.getAddressLine1() != null
								&& this.getAddressLine1().equals(castOther.getAddressLine1())))
				&& ((this.getAddressLine2() == castOther.getAddressLine2())
						|| (this.getAddressLine2() != null && castOther.getAddressLine2() != null
								&& this.getAddressLine2().equals(castOther.getAddressLine2())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getZipCode() == castOther.getZipCode()) || (this.getZipCode() != null
						&& castOther.getZipCode() != null && this.getZipCode().equals(castOther.getZipCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOperation() == null ? 0 : this.getOperation().hashCode());
		result = 37 * result + (getProcessDate() == null ? 0 : this.getProcessDate().hashCode());
		result = 37 * result + this.getServerId();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getAssetTag() == null ? 0 : this.getAssetTag().hashCode());
		result = 37 * result + (getSystemType() == null ? 0 : this.getSystemType().hashCode());
		result = 37 * result + (getEquipmentType() == null ? 0 : this.getEquipmentType().hashCode());
		result = 37 * result + (getAddressLine1() == null ? 0 : this.getAddressLine1().hashCode());
		result = 37 * result + (getAddressLine2() == null ? 0 : this.getAddressLine2().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getZipCode() == null ? 0 : this.getZipCode().hashCode());
		return result;
	}

}
