package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemSensitivityTblAudit generated by hbm2java
 */
@Entity
@Table(name = "system_sensitivity_tbl_audit")
public class SystemSensitivityAuditEntity implements java.io.Serializable {
	
	private int systemSensitivityAuditId;
	private String operation;
	private Date processDate;
	private int systemSensitivityId;
	private String systemSensitivityValue;
	private String description;
	private Integer createdBy;
	private Date createdTs;
	private Integer appSystemSensitivity;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "system_sensitivity_audit_id", unique = true, nullable = false)
	public int getSystemSensitivityAuditId() {
		return systemSensitivityAuditId;
	}

	public void setSystemSensitivityAuditId(int systemSensitivityAuditId) {
		this.systemSensitivityAuditId = systemSensitivityAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "SYSTEM_SENSITIVITY_ID", nullable = false)
	public int getSystemSensitivityId() {
		return this.systemSensitivityId;
	}

	public void setSystemSensitivityId(int systemSensitivityId) {
		this.systemSensitivityId = systemSensitivityId;
	}

	@Column(name = "SYSTEM_SENSITIVITY_VALUE", length = 100)
	public String getSystemSensitivityValue() {
		return this.systemSensitivityValue;
	}

	public void setSystemSensitivityValue(String systemSensitivityValue) {
		this.systemSensitivityValue = systemSensitivityValue;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}
	@Column(name = "app_system_sensitivity")
	public Integer getAppSystemSensitivity() {
		return this.appSystemSensitivity;
	}

	public void setAppSystemSensitivity(Integer appSystemSensitivity) {
		this.appSystemSensitivity = appSystemSensitivity;
	}

	
}
