package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TechnologiesTbAudit generated by hbm2java
 */
@Entity
@Table(name = "technologies_tb_audit")
public class TechnologiesAuditEntity implements java.io.Serializable {

	private int technologiesAuditId;
	private String operation;
	private Date processDate;
	private int technologyId;
	private String name;
	private String technologyVersion;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "technologies_audit_id", unique = true, nullable = false)
	public int getTechnologiesAuditId() {
		return technologiesAuditId;
	}

	public void setTechnologiesAuditId(int technologiesAuditId) {
		this.technologiesAuditId = technologiesAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "technology_id", nullable = false)
	public int getTechnologyId() {
		return this.technologyId;
	}

	public void setTechnologyId(int technologyId) {
		this.technologyId = technologyId;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "technology_version", length = 45)
	public String getTechnologyVersion() {
		return this.technologyVersion;
	}

	public void setTechnologyVersion(String technologyVersion) {
		this.technologyVersion = technologyVersion;
	}

}
