package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserTblAudit generated by hbm2java
 */
@Entity
@Table(name = "user_tbl_audit")
public class UserAuditEntity implements java.io.Serializable {

	private int userAuditId;
	private String operation;
	private Date processDate;
	private int userId;
	private String loginId;
	private String password;
	private String firstName;
	private String lastName;
	private String phoneNumber;
	private String emailId;
	private String title;
	private Date createdTs;
	private String createdBy;
	private Date modifiedTs;
	private String modifiedBy;
	private Integer officeTblOfficeId;
	private Integer appRoleId;
	private Integer iamId;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_audit_id", unique = true, nullable = false)
	public int getUserAuditId() {
		return userAuditId;
	}

	public void setUserAuditId(int userAuditId) {
		this.userAuditId = userAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "LOGIN_ID", length = 100)
	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Column(name = "PASSWORD", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "FIRST_NAME", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "PHONE_NUMBER", length = 100)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "EMAIL_ID", length = 200)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "TITLE", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "CREATED_BY", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "MODIFIED_TS", length = 19)
	public Date getModifiedTs() {
		return this.modifiedTs;
	}

	public void setModifiedTs(Date modifiedTs) {
		this.modifiedTs = modifiedTs;
	}

	@Column(name = "MODIFIED_BY", length = 100)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "OFFICE_TBL_OFFICE_ID")
	public Integer getOfficeTblOfficeId() {
		return this.officeTblOfficeId;
	}

	public void setOfficeTblOfficeId(Integer officeTblOfficeId) {
		this.officeTblOfficeId = officeTblOfficeId;
	}

	@Column(name = "APP_ROLE_ID")
	public Integer getAppRoleId() {
		return this.appRoleId;
	}

	public void setAppRoleId(Integer appRoleId) {
		this.appRoleId = appRoleId;
	}

	@Column(name = "IAM_ID")
	public Integer getIamId() {
		return this.iamId;
	}

	public void setIamId(Integer iamId) {
		this.iamId = iamId;
	}
}
