package com.soch.Integra.entities.audit;
// Generated Oct 20, 2017 10:15:53 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserAppRoleTblAudit generated by hbm2java
 */
@Entity
@Table(name = "user_app_role_tbl_audit")
public class UserAppRoleAuditEntity implements java.io.Serializable {
	
	private int userAppRoleAuditId;
	private String operation;
	private Date processDate;
	private int appRoleId;
	private String name;
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_app_role_audit_id", unique = true, nullable = false)
	public int getUserAppRoleAuditId() {
		return userAppRoleAuditId;
	}

	public void setUserAppRoleAuditId(int userAppRoleAuditId) {
		this.userAppRoleAuditId = userAppRoleAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "APP_ROLE_ID", nullable = false)
	public int getAppRoleId() {
		return this.appRoleId;
	}

	public void setAppRoleId(int appRoleId) {
		this.appRoleId = appRoleId;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
