package com.soch.Integra.dto;
// default package
// Generated Sep 22, 2017 2:31:09 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AppBusinessOwnerTbl generated by hbm2java
 */

public class AppBusinessOwnerDTO implements java.io.Serializable {

	private Integer appBusinessOwnerId;
	private boolean activeFlag;
	public Integer getAppBusinessOwnerId() {
		return appBusinessOwnerId;
	}
	public void setAppBusinessOwnerId(Integer appBusinessOwnerId) {
		this.appBusinessOwnerId = appBusinessOwnerId;
	}
	public boolean isActiveFlag() {
		return activeFlag;
	}
	public void setActiveFlag(boolean activeFlag) {
		this.activeFlag = activeFlag;
	}
	
	
	

}
