package com.soch.Integra.dto;
// default package
// Generated Dec 16, 2017 11:08:41 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.List;


/**
 * AssessmentTbl generated by hbm2java
 */
public class AssessmentDTO {

	private Integer assessmentId;
	private String name;
	private Date assessmentDt;
	private String status;
	private Date nextAssessmentDt;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private String auditName;
	private Date updatedTs;
	private int applicationID;
	private int policyGrpId;
	private int auditId;
	private String appAcronym;
	private int appId;
	private String policyName;
	private List<AssessmentPolicyDTO> assessmentPolicyDTOs;
	private List<AssessmentFileDTO> assessmentFileDTOs;
	private String typeOfFindings;
	private String overallRiskLevel;
	private String findingComments;
	private String responsibleParty;
	private String recomendedBy;
	private Date estimatedCompletionDt;
	private String responseBy;
	private Date responseDt;
	private Date actionPlanStartDt;
	private Date actionPlanEndDt;
	private String actionPlanAssignedTo;
	private String actionPlanSummary;
	private String actionPlanTasks;
	private String actionPlanCloseoutComments;
	private String findingDescription;
	private String comments;
	private String recomendations;
	private String managementReponse;
	private String closeOutComments;
	private String securityRisks;
	private String budgetDescription;
	private double budget;
	private String businessRisks;
	private String lessonsLearnedDescription;
	private String lessonsEnteredBy;
	private Date lessonsEnteredDate; 
	
	public String getLessonsLearnedDescription() {
		return lessonsLearnedDescription;
	}

	public void setLessonsLearnedDescription(String lessonsLearnedDescription) {
		this.lessonsLearnedDescription = lessonsLearnedDescription;
	}

	public String getLessonsEnteredBy() {
		return lessonsEnteredBy;
	}

	public void setLessonsEnteredBy(String lessonsEnteredBy) {
		this.lessonsEnteredBy = lessonsEnteredBy;
	}

	public Date getLessonsEnteredDate() {
		return lessonsEnteredDate;
	}

	public void setLessonsEnteredDate(Date lessonsEnteredDate) {
		this.lessonsEnteredDate = lessonsEnteredDate;
	}

	public Integer getAssessmentId() {
		return this.assessmentId;
	}

	public void setAssessmentId(Integer assessmentId) {
		this.assessmentId = assessmentId;
	}

	public String getName() {
		return this.name;
	}

	
	public void setName(String name) {
		this.name = name;
	}

	public Date getAssessmentDt() {
		return this.assessmentDt;
	}

	public void setAssessmentDt(Date assessmentDt) {
		this.assessmentDt = assessmentDt;
	}

	public Date getNextAssessmentDt() {
		return this.nextAssessmentDt;
	}

	public void setNextAssessmentDt(Date nextAssessmentDt) {
		this.nextAssessmentDt = nextAssessmentDt;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

	public int getApplicationID() {
		return applicationID;
	}

	public void setApplicationID(int applicationID) {
		this.applicationID = applicationID;
	}

	public int getPolicyGrpId() {
		return policyGrpId;
	}

	public void setPolicyGrpId(int policyGrpId) {
		this.policyGrpId = policyGrpId;
	}

	public List<AssessmentPolicyDTO> getAssessmentPolicyDTOs() {
		return assessmentPolicyDTOs;
	}

	public void setAssessmentPolicyDTOs(List<AssessmentPolicyDTO> assessmentPolicyDTOs) {
		this.assessmentPolicyDTOs = assessmentPolicyDTOs;
	}

	public int getAuditId() {
		return auditId;
	}

	public void setAuditId(int auditId) {
		this.auditId = auditId;
	}

	public String getAuditName() {
		return auditName;
	}

	public void setAuditName(String auditName) {
		this.auditName = auditName;
	}

	public String getAppAcronym() {
		return appAcronym;
	}

	public void setAppAcronym(String appAcronym) {
		this.appAcronym = appAcronym;
	}

	public int getAppId() {
		return appId;
	}

	public void setAppId(int appId) {
		this.appId = appId;
	}

	public String getPolicyName() {
		return policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	public String getTypeOfFindings() {
		return typeOfFindings;
	}

	public String getOverallRiskLevel() {
		return overallRiskLevel;
	}

	public String getFindingComments() {
		return findingComments;
	}

	public String getResponsibleParty() {
		return responsibleParty;
	}

	public String getRecomendedBy() {
		return recomendedBy;
	}

	public Date getEstimatedCompletionDt() {
		return estimatedCompletionDt;
	}

	public String getResponseBy() {
		return responseBy;
	}

	public Date getResponseDt() {
		return responseDt;
	}

	public Date getActionPlanStartDt() {
		return actionPlanStartDt;
	}

	public Date getActionPlanEndDt() {
		return actionPlanEndDt;
	}

	public String getActionPlanAssignedTo() {
		return actionPlanAssignedTo;
	}

	public String getActionPlanSummary() {
		return actionPlanSummary;
	}

	public String getActionPlanTasks() {
		return actionPlanTasks;
	}

	public String getActionPlanCloseoutComments() {
		return actionPlanCloseoutComments;
	}

	public String getFindingDescription() {
		return findingDescription;
	}

	public String getComments() {
		return comments;
	}

	public String getRecomendations() {
		return recomendations;
	}

	public String getManagementReponse() {
		return managementReponse;
	}

	public String getCloseOutComments() {
		return closeOutComments;
	}

	public String getSecurityRisks() {
		return securityRisks;
	}

	public String getBudgetDescription() {
		return budgetDescription;
	}

	public void setTypeOfFindings(String typeOfFindings) {
		this.typeOfFindings = typeOfFindings;
	}

	public void setOverallRiskLevel(String overallRiskLevel) {
		this.overallRiskLevel = overallRiskLevel;
	}

	public void setFindingComments(String findingComments) {
		this.findingComments = findingComments;
	}

	public void setResponsibleParty(String responsibleParty) {
		this.responsibleParty = responsibleParty;
	}

	public void setRecomendedBy(String recomendedBy) {
		this.recomendedBy = recomendedBy;
	}

	public void setEstimatedCompletionDt(Date estimatedCompletionDt) {
		this.estimatedCompletionDt = estimatedCompletionDt;
	}

	public void setResponseBy(String responseBy) {
		this.responseBy = responseBy;
	}

	public void setResponseDt(Date responseDt) {
		this.responseDt = responseDt;
	}

	public void setActionPlanStartDt(Date actionPlanStartDt) {
		this.actionPlanStartDt = actionPlanStartDt;
	}

	public void setActionPlanEndDt(Date actionPlanEndDt) {
		this.actionPlanEndDt = actionPlanEndDt;
	}

	public void setActionPlanAssignedTo(String actionPlanAssignedTo) {
		this.actionPlanAssignedTo = actionPlanAssignedTo;
	}

	public void setActionPlanSummary(String actionPlanSummary) {
		this.actionPlanSummary = actionPlanSummary;
	}

	public void setActionPlanTasks(String actionPlanTasks) {
		this.actionPlanTasks = actionPlanTasks;
	}

	public void setActionPlanCloseoutComments(String actionPlanCloseoutComments) {
		this.actionPlanCloseoutComments = actionPlanCloseoutComments;
	}

	public void setFindingDescription(String findingDescription) {
		this.findingDescription = findingDescription;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public void setRecomendations(String recomendations) {
		this.recomendations = recomendations;
	}

	public void setManagementReponse(String managementReponse) {
		this.managementReponse = managementReponse;
	}

	public void setCloseOutComments(String closeOutComments) {
		this.closeOutComments = closeOutComments;
	}

	public void setSecurityRisks(String securityRisks) {
		this.securityRisks = securityRisks;
	}

	public void setBudgetDescription(String budgetDescription) {
		this.budgetDescription = budgetDescription;
	}

	public double getBudget() {
		return budget;
	}

	public void setBudget(double budget) {
		this.budget = budget;
	}

	public String getBusinessRisks() {
		return businessRisks;
	}

	public void setBusinessRisks(String businessRisks) {
		this.businessRisks = businessRisks;
	}

	public List<AssessmentFileDTO> getAssessmentFileDTOs() {
		return assessmentFileDTOs;
	}

	public void setAssessmentFileDTOs(List<AssessmentFileDTO> assessmentFileDTOs) {
		this.assessmentFileDTOs = assessmentFileDTOs;
	}

	
	
}
