package com.soch.Integra.dto;
// default package
// Generated Dec 16, 2017 11:08:41 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;


/**
 * AssessmentPolicyTbl generated by hbm2java
 */
public class AssessmentPolicyDTO{

	private Integer assessmentPolicyId;
	private PolicyDTO policyDTO;
	private boolean confidentiality;
	private boolean integrity;
	private boolean availability;
	private Date completionDt;
	private String vulnerabilityFamily;
	private String riskVulnerability;
	private String riskThreat;
	private String riskSummary;
	private String impactMagnitude;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;
	private String cyberSecurityFramework;
	private String controlsInPlace;
	private String applicationName;
	private String status;

	public Integer getAssessmentPolicyId() {
		return this.assessmentPolicyId;
	}

	public void setAssessmentPolicyId(Integer assessmentPolicyId) {
		this.assessmentPolicyId = assessmentPolicyId;
	}

	public boolean getConfidentiality() {
		return this.confidentiality;
	}

	public void setConfidentiality(boolean confidentiality) {
		this.confidentiality = confidentiality;
	}

	public boolean getIntegrity() {
		return this.integrity;
	}

	public void setIntegrity(boolean integrity) {
		this.integrity = integrity;
	}

	public boolean getAvailability() {
		return this.availability;
	}

	public void setAvailability(boolean availability) {
		this.availability = availability;
	}

	public Date getCompletionDt() {
		return this.completionDt;
	}

	public void setCompletionDt(Date completionDt) {
		this.completionDt = completionDt;
	}

	public String getVulnerabilityFamily() {
		return this.vulnerabilityFamily;
	}

	public void setVulnerabilityFamily(String vulnerabilityFamily) {
		this.vulnerabilityFamily = vulnerabilityFamily;
	}

	public String getRiskVulnerability() {
		return this.riskVulnerability;
	}

	public void setRiskVulnerability(String riskVulnerability) {
		this.riskVulnerability = riskVulnerability;
	}

	public String getRiskSummary() {
		return this.riskSummary;
	}

	public void setRiskSummary(String riskSummary) {
		this.riskSummary = riskSummary;
	}

	public String getImpactMagnitude() {
		return this.impactMagnitude;
	}

	public void setImpactMagnitude(String impactMagnitude) {
		this.impactMagnitude = impactMagnitude;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

	public PolicyDTO getPolicyDTO() {
		return policyDTO;
	}

	public void setPolicyDTO(PolicyDTO policyDTO) {
		this.policyDTO = policyDTO;
	}

	public String getCyberSecurityFramework() {
		return cyberSecurityFramework;
	}

	public void setCyberSecurityFramework(String cyberSecurityFramework) {
		this.cyberSecurityFramework = cyberSecurityFramework;
	}

	public String getRiskThreat() {
		return riskThreat;
	}

	public void setRiskThreat(String riskThreat) {
		this.riskThreat = riskThreat;
	}

	public String getControlsInPlace() {
		return controlsInPlace;
	}

	public void setControlsInPlace(String controlsInPlace) {
		this.controlsInPlace = controlsInPlace;
	}

	public String getApplicationName() {
		return applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
}
