package com.soch.Integra.dto;
// default package
// Generated Feb 22, 2018 3:06:29 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * AssessmentFileTbl generated by hbm2java
 */
public class AssessmentFileDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -763780294873052681L;
	private Integer assessmentFileId;
	private String fileName;
	private String fileLocation;
	private String fileContent;
	private boolean status;
	private String createdBy;
	private Date createdTs;

	
	
	public Integer getAssessmentFileId() {
		return this.assessmentFileId;
	}

	public void setAssessmentFileId(Integer assessmentFileId) {
		this.assessmentFileId = assessmentFileId;
	}


	public String getFileName() {
		return this.fileName;
	}

	
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileLocation() {
		return this.fileLocation;
	}

	public void setFileLocation(String fileLocation) {
		this.fileLocation = fileLocation;
	}

	public boolean getStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	public String getFileContent() {
		return fileContent;
	}

	public void setFileContent(String fileContent) {
		this.fileContent = fileContent;
	}
	
	

}
