package com.soch.Integra.dto;
// Generated Apr 20, 2018 1:01:13 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * VendorAddressTbl generated by hbm2java
 */
public class VendorAddressDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6140115422197954356L;
	
	private Integer addressId;
	private String streetName;
	private String city;
	private String state;
	private String zipcode;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;

	
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}


	public String getStreetName() {
		return this.streetName;
	}

	
	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

}
