package com.soch.Integra.dto;
// Generated Apr 20, 2018 1:01:13 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * VendorsTbl generated by hbm2java
 */
public class VendorsDTO implements java.io.Serializable {

	private Integer vendorId;
	private String name;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;
	private VendorAddressDTO vendorAddress;
	private VendorContactDTO vendorContact;

	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

	public VendorAddressDTO getVendorAddress() {
		return vendorAddress;
	}

	public void setVendorAddress(VendorAddressDTO vendorAddress) {
		this.vendorAddress = vendorAddress;
	}

	public VendorContactDTO getVendorContact() {
		return vendorContact;
	}

	public void setVendorContact(VendorContactDTO vendorContact) {
		this.vendorContact = vendorContact;
	}

}
