package com.soch.Integra.vendors.dto;
// Generated Apr 23, 2018 2:33:22 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.List;

import com.soch.Integra.dto.VendorsDTO;

/**
 * SolutionsTbl generated by hbm2java
 */
public class SolutionsDTO implements java.io.Serializable {

	private Integer solutionId;
	private Date certDt;
	private String certStadard;
	private Date certRenewalDueDt;
	private String name;
	private String versionNumber;
	private String patches;
	private String notes;
	private Integer solutionType;
	private Integer vendorId;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;
	private VendorsDTO vendor;
	private String solutionTypeName;
	private int labVendorId;
	private HostingTypeDTO hostingTypeDTO;
	private List<CertDocDTO> certDocDTOs;
	private SystemTypeDTO systemTypeDTO;
	private LabVendorsDTO labVendorsDTO;
	private String hostingTypeNotes;
	private int precinctTypeId;
	private String precinctTypeName;
	
	public Integer getSolutionId() {
		return this.solutionId;
	}

	public void setSolutionId(Integer solutionId) {
		this.solutionId = solutionId;
	}

	public Date getCertDt() {
		return this.certDt;
	}

	public void setCertDt(Date certDt) {
		this.certDt = certDt;
	}

	public String getCertStadard() {
		return this.certStadard;
	}

	public void setCertStadard(String certStadard) {
		this.certStadard = certStadard;
	}

	public Date getCertRenewalDueDt() {
		return this.certRenewalDueDt;
	}

	public void setCertRenewalDueDt(Date certRenewalDueDt) {
		this.certRenewalDueDt = certRenewalDueDt;
	}

	public String getVersionNumber() {
		return this.versionNumber;
	}
	
	

	public int getPrecinctTypeId() {
		return precinctTypeId;
	}

	public void setPrecinctTypeId(int precinctTypeId) {
		this.precinctTypeId = precinctTypeId;
	}

	public void setVersionNumber(String versionNumber) {
		this.versionNumber = versionNumber;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPatches() {
		return this.patches;
	}

	public void setPatches(String patches) {
		this.patches = patches;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Integer getSolutionType() {
		return solutionType;
	}

	public void setSolutionType(Integer solutionType) {
		this.solutionType = solutionType;
	}

	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

	public List<CertDocDTO> getCertDocDTOs() {
		return certDocDTOs;
	}

	public void setCertDocDTOs(List<CertDocDTO> certDocDTOs) {
		this.certDocDTOs = certDocDTOs;
	}

	public String getSolutionTypeName() {
		return solutionTypeName;
	}

	public void setSolutionTypeName(String solutionTypeName) {
		this.solutionTypeName = solutionTypeName;
	}

	public VendorsDTO getVendor() {
		return vendor;
	}

	public void setVendor(VendorsDTO vendor) {
		this.vendor = vendor;
	}

	public int getLabVendorId() {
		return labVendorId;
	}

	public void setLabVendorId(int labVendorId) {
		this.labVendorId = labVendorId;
	}

	public LabVendorsDTO getLabVendorsDTO() {
		return labVendorsDTO;
	}

	public void setLabVendorsDTO(LabVendorsDTO labVendorsDTO) {
		this.labVendorsDTO = labVendorsDTO;
	}

	public SystemTypeDTO getSystemTypeDTO() {
		return systemTypeDTO;
	}

	public void setSystemTypeDTO(SystemTypeDTO systemTypeDTO) {
		this.systemTypeDTO = systemTypeDTO;
	}

	public HostingTypeDTO getHostingTypeDTO() {
		return hostingTypeDTO;
	}

	public void setHostingTypeDTO(HostingTypeDTO hostingTypeDTO) {
		this.hostingTypeDTO = hostingTypeDTO;
	}

	public String getHostingTypeNotes() {
		return hostingTypeNotes;
	}

	public void setHostingTypeNotes(String hostingTypeNotes) {
		this.hostingTypeNotes = hostingTypeNotes;
	}

	public String getPrecinctTypeName() {
		return precinctTypeName;
	}

	public void setPrecinctTypeName(String precinctTypeName) {
		this.precinctTypeName = precinctTypeName;
	}
	
	
	
}
