package com.soch.Integra.entities;
// default package
// Generated Sep 20, 2017 12:11:19 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppAuditPolicyTb generated by hbm2java
 */
@Entity
@Table(name = "app_audit_policy_tbl")
public class AppAuditPolicyEntity implements java.io.Serializable {

	private Integer appAuditPolicyId;
	private AppAuditEntity appAuditEntity;
	private PolicyEntity policyEntity;
	private String defaultVal;
	private String status;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "app_audit_policy_id", unique = true, nullable = false)
	public Integer getAppAuditPolicyId() {
		return this.appAuditPolicyId;
	}

	public void setAppAuditPolicyId(Integer appAuditPolicyId) {
		this.appAuditPolicyId = appAuditPolicyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUDIT_ID")
	public AppAuditEntity getAppAuditEntity() {
		return appAuditEntity;
	}

	public void setAppAuditEntity(AppAuditEntity appAuditEntity) {
		this.appAuditEntity = appAuditEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POLICY_ID")
	public PolicyEntity getPolicyEntity() {
		return policyEntity;
	}

	public void setPolicyEntity(PolicyEntity policyEntity) {
		this.policyEntity = policyEntity;
	}


	@Column(name = "default_val", length = 100)
	public String getDefaultVal() {
		return this.defaultVal;
	}

	public void setDefaultVal(String defaultVal) {
		this.defaultVal = defaultVal;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "created_by", length = 200)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_ts", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "updated_by", length = 200)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_ts", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

}
