package com.soch.Integra.entities;
// default package
// Generated Sep 7, 2017 10:39:33 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppAuditFileTbl generated by hbm2java
 */
@Entity
@Table(name = "app_audit_file_tbl")
public class AppAuditFileEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8477051165936183846L;
	private Integer appAuditFileId;
	private AppAuditEntity appAuditEntity;
	private String fileName;
	private byte[] fileContent;
	private boolean status;
	private String createdBy;
	private Date createdTs;

	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "app_audit_file_id", unique = true, nullable = false)
	public Integer getAppAuditFileId() {
		return this.appAuditFileId;
	}

	public void setAppAuditFileId(Integer appAuditFileId) {
		this.appAuditFileId = appAuditFileId;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "AUDIT_ID")
	public AppAuditEntity getAppAuditEntity() {
		return appAuditEntity;
	}

	public void setAppAuditEntity(AppAuditEntity appAuditEntity) {
		this.appAuditEntity = appAuditEntity;
	}

	@Column(name = "file_name", length = 100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_content")
	public byte[] getFileContent() {
		return this.fileContent;
	}

	public void setFileContent(byte[] fileContent) {
		this.fileContent = fileContent;
	}

	@Column(name = "status", length = 1)
	public boolean getStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 200)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

}
