package com.soch.Integra.entities;
// Generated Apr 25, 2017 12:37:56 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ApplicationTblId generated by hbm2java
 */
@Embeddable
public class ApplicationEntityId implements java.io.Serializable {

	private int applicationId;
	private int officeTblOfficeId;
	private int divisionTblDivisionId;

	public ApplicationEntityId() {
	}

	public ApplicationEntityId(int applicationId, int officeTblOfficeId, int divisionTblDivisionId) {
		this.applicationId = applicationId;
		this.officeTblOfficeId = officeTblOfficeId;
		this.divisionTblDivisionId = divisionTblDivisionId;
	}

	@Column(name = "APPLICATION_ID", nullable = false)
	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "OFFICE_TBL_OFFICE_ID", nullable = false)
	public int getOfficeTblOfficeId() {
		return this.officeTblOfficeId;
	}

	public void setOfficeTblOfficeId(int officeTblOfficeId) {
		this.officeTblOfficeId = officeTblOfficeId;
	}

	@Column(name = "DIVISION_TBL_DIVISION_ID", nullable = false)
	public int getDivisionTblDivisionId() {
		return this.divisionTblDivisionId;
	}

	public void setDivisionTblDivisionId(int divisionTblDivisionId) {
		this.divisionTblDivisionId = divisionTblDivisionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ApplicationEntityId))
			return false;
		ApplicationEntityId castOther = (ApplicationEntityId) other;

		return (this.getApplicationId() == castOther.getApplicationId())
				&& (this.getOfficeTblOfficeId() == castOther.getOfficeTblOfficeId())
				&& (this.getDivisionTblDivisionId() == castOther.getDivisionTblDivisionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getApplicationId();
		result = 37 * result + this.getOfficeTblOfficeId();
		result = 37 * result + this.getDivisionTblDivisionId();
		return result;
	}

}
