package com.soch.Integra.entities;
// Generated Apr 25, 2017 12:37:56 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ApplicationDatabaseTbl generated by hbm2java
 */
@Entity
@Table(name = "application_database_tbl")
public class ApplicationDatabaseEntity implements java.io.Serializable {

	private int applicationDatabaseid;
	private ApplicationEntity applicationEntity;
	private DatabaseEntity databaseEntity;
	private UserEntity userEntityByAdministrator;
	private UserEntity userEntityByCreatedBy;
	private UserEntity custodian;
	private String technologies;
	private Date createdTs;
	private boolean activityFlag;

	public ApplicationDatabaseEntity() {
	}

	public ApplicationDatabaseEntity(int applicationDatabaseid) {
		this.applicationDatabaseid = applicationDatabaseid;
	}

	public ApplicationDatabaseEntity(int applicationDatabaseid, ApplicationEntity applicationEntity, DatabaseEntity databaseEntity,
			UserEntity userEntityByAdministrator, UserEntity userEntityByCreatedBy, UserEntity custodian, String technologies,
			Date createdTs) {
		this.applicationDatabaseid = applicationDatabaseid;
		this.applicationEntity = applicationEntity;
		this.databaseEntity = databaseEntity;
		this.userEntityByAdministrator = userEntityByAdministrator;
		this.userEntityByCreatedBy = userEntityByCreatedBy;
		this.custodian = custodian;
		this.technologies = technologies;
		this.createdTs = createdTs;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "APPLICATION_DATABASE_ID", unique = true, nullable = false)
	public int getApplicationDatabaseid() {
		return this.applicationDatabaseid;
	}

	public void setApplicationDatabaseid(int applicationDatabaseid) {
		this.applicationDatabaseid = applicationDatabaseid;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "APPLICATION_ID")
	public ApplicationEntity getApplicationEntity() {
		return this.applicationEntity;
	}

	public void setApplicationEntity(ApplicationEntity applicationEntity) {
		this.applicationEntity = applicationEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "DATABASE_ID")
	public DatabaseEntity getDatabaseEntity() {
		return this.databaseEntity;
	}

	public void setDatabaseEntity(DatabaseEntity databaseEntity) {
		this.databaseEntity = databaseEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "ADMINISTRATOR")
	public UserEntity getUserEntityByAdministrator() {
		return this.userEntityByAdministrator;
	}

	public void setUserEntityByAdministrator(UserEntity userEntityByAdministrator) {
		this.userEntityByAdministrator = userEntityByAdministrator;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "CREATED_BY")
	public UserEntity getUserEntityByCreatedBy() {
		return this.userEntityByCreatedBy;
	}

	public void setUserEntityByCreatedBy(UserEntity userEntityByCreatedBy) {
		this.userEntityByCreatedBy = userEntityByCreatedBy;
	}
	
	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "DATA_CUSTODIAN")
	public UserEntity getCustodian() {
		return this.custodian;
	}

	public void setCustodian(UserEntity custodian) {
		this.custodian = custodian;
	}

	@Column(name = "TECHNOLOGIES")
	public String getTechnologies() {
		return this.technologies;
	}

	public void setTechnologies(String technologies) {
		this.technologies = technologies;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}
	
	@Column(name = "ACTIVITY_FLAG")
	public boolean isActivityFlag() {
		return activityFlag;
	}

	public void setActivityFlag(boolean activityFlag) {
		this.activityFlag = activityFlag;
	}

}
