package com.soch.Integra.entities;
// Generated Apr 25, 2017 12:37:56 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ApplicationServerTbl generated by hbm2java
 */
@Entity
@Table(name = "application_server_tbl")
public class ApplicationServerEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3679750955412870007L;
	private int applicationServerId;
	private ApplicationEntity applicationEntity;
	private ServerEntity serverEntity;
	private boolean activityFlag;

	public ApplicationServerEntity() {
	}

	public ApplicationServerEntity(int applicationServerId) {
		this.applicationServerId = applicationServerId;
	}

	public ApplicationServerEntity(int applicationServerId, ApplicationEntity applicationEntity, ServerEntity serverEntity) {
		this.applicationServerId = applicationServerId;
		this.applicationEntity = applicationEntity;
		this.serverEntity = serverEntity;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "APPLICATION_SERVER_ID", unique = true, nullable = false)
	public int getApplicationServerId() {
		return this.applicationServerId;
	}

	public void setApplicationServerId(int applicationServerId) {
		this.applicationServerId = applicationServerId;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "APPLICATION_ID")
	public ApplicationEntity getApplicationEntity() {
		return this.applicationEntity;
	}

	public void setApplicationEntity(ApplicationEntity applicationEntity) {
		this.applicationEntity = applicationEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "SERVER_ID")
	public ServerEntity getServerEntity() {
		return this.serverEntity;
	}

	public void setServerEntity(ServerEntity serverEntity) {
		this.serverEntity = serverEntity;
	}
	
	@Column(name = "ACTIVITY_FLAG")
	public boolean isActivityFlag() {
		return activityFlag;
	}

	public void setActivityFlag(boolean activityFlag) {
		this.activityFlag = activityFlag;
	}

}
