package com.soch.Integra.entities;
// Generated May 1, 2018 11:47:56 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppSolutionDeviceTbl generated by hbm2java
 */
@Entity
@Table(name = "app_solution_device_tbl")
public class AppSolutionDeviceEntity implements java.io.Serializable {

	private Integer appSolutionDevice;
	private AppSolutionEntity appSolutionEntity;
	private String modelNumber;
	private String serialNumber;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;
	private boolean activeFlag;
	private String firstName;
	private String lastName;
	private String street1;
	private String street2;
	private String city;
	private String state;
	private String zipCode;
	private String scanningStatus;
	private Date nextScanningDt;
	private Date currentScanningDt;
	private String overallStatus;
	private String notes;
	private Integer appSolutionId;
	private Set<DeviceDocEntity> deviceDocEntities = new HashSet<DeviceDocEntity>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "APP_SOLUTION_DEVICE", unique = true, nullable = false)
	public Integer getAppSolutionDevice() {
		return this.appSolutionDevice;
	}

	public void setAppSolutionDevice(Integer appSolutionDevice) {
		this.appSolutionDevice = appSolutionDevice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APP_SOLUTION_ID")
	public AppSolutionEntity getAppSolutionEntity() {
		return appSolutionEntity;
	}

	public void setAppSolutionEntity(AppSolutionEntity appSolutionEntity) {
		this.appSolutionEntity = appSolutionEntity;
	}

	@Column(name = "MODEL_NUMBER", length = 200)
	public String getModelNumber() {
		return this.modelNumber;
	}

	public void setModelNumber(String modelNumber) {
		this.modelNumber = modelNumber;
	}

	@Column(name = "SERIAL_NUMBER", length = 200)
	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	@Column(name = "CREATED_BY", length = 200)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "UPDATED_BY", length = 200)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_TS", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}
	
	@Column(name = "ACTIVE_FLAG", length = 1)
	public boolean getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(boolean activeFlag) {
		this.activeFlag = activeFlag;
	}
	
	 @Column(name="FIRST_NAME", length=200)
	    public String getFirstName() {
	        return this.firstName;
	    }
	    
	    public void setFirstName(String firstName) {
	        this.firstName = firstName;
	    }

	    
	    @Column(name="LAST_NAME", length=200)
	    public String getLastName() {
	        return this.lastName;
	    }
	    
	    public void setLastName(String lastName) {
	        this.lastName = lastName;
	    }

	    
	    @Column(name="STREET1", length=200)
	    public String getStreet1() {
	        return this.street1;
	    }
	    
	    public void setStreet1(String street1) {
	        this.street1 = street1;
	    }

	    
	    @Column(name="STREET2", length=200)
	    public String getStreet2() {
	        return this.street2;
	    }
	    
	    public void setStreet2(String street2) {
	        this.street2 = street2;
	    }

	    
	    @Column(name="CITY", length=100)
	    public String getCity() {
	        return this.city;
	    }
	    
	    public void setCity(String city) {
	        this.city = city;
	    }

	    
	    @Column(name="STATE", length=100)
	    public String getState() {
	        return this.state;
	    }
	    
	    public void setState(String state) {
	        this.state = state;
	    }

	    
	    @Column(name="ZIP_CODE", length=20)
	    public String getZipCode() {
	        return this.zipCode;
	    }
	    
	    public void setZipCode(String zipCode) {
	        this.zipCode = zipCode;
	    }
	    
	    @Column(name="SCANNING_STATUS")
		public String getScanningStatus() {
			return scanningStatus;
		}

		public void setScanningStatus(String scanningStatus) {
			this.scanningStatus = scanningStatus;
		}
		
		 @Column(name="NEXT_SCANNING_DT")
		public Date getNextScanningDt() {
			return nextScanningDt;
		}

		public void setNextScanningDt(Date nextScanningDt) {
			this.nextScanningDt = nextScanningDt;
		}
		
		
		 @Column(name="CURRENT_SCANNING_DT")
			public Date getCurrentScanningDt() {
				return currentScanningDt;
			}

			public void setCurrentScanningDt(Date currentScanningDt) {
				this.currentScanningDt = currentScanningDt;
			}
		
		 @Column(name="OVERALL_STATUS")
		public String getOverallStatus() {
			return overallStatus;
		}
		
		public void setOverallStatus(String overallStatus) {
			this.overallStatus = overallStatus;
		}
		
		@Column(name="NOTES")
		public String getNotes() {
			return notes;
		}

		public void setNotes(String notes) {
			this.notes = notes;
		}
		
		@OneToMany(fetch = FetchType.LAZY, mappedBy="appSolutionDeviceEntity", cascade=CascadeType.ALL)
		public Set<DeviceDocEntity> getDeviceDocEntities() {
			return deviceDocEntities;
		}

		public void setDeviceDocEntities(Set<DeviceDocEntity> deviceDocEntities) {
			this.deviceDocEntities = deviceDocEntities;
		}

		
}
