package com.soch.Integra.entities;
// Generated May 17, 2017 1:52:58 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppStatusTbl generated by hbm2java
 */
@Entity
@Table(name = "app_status_tbl")
public class AppStatusEntity implements java.io.Serializable {

	private Integer appStatusTblId;
	private ApplicationEntity applicationEntity;
	private int updatedSection;
	private Date updatedTs;
	private Date createdTs;
	private String comments;

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "app_status_tbl_id", unique = true, nullable = false)
	public Integer getAppStatusTblId() {
		return this.appStatusTblId;
	}

	public void setAppStatusTblId(Integer appStatusTblId) {
		this.appStatusTblId = appStatusTblId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "application_id")
	public ApplicationEntity getApplicationEntity() {
		return applicationEntity;
	}

	public void setApplicationEntity(ApplicationEntity applicationEntity) {
		this.applicationEntity = applicationEntity;
	}



	@Column(name = "updated_section", length = 45)
	public int getUpdatedSection() {
		return this.updatedSection;
	}

	

	public void setUpdatedSection(int updatedSection) {
		this.updatedSection = updatedSection;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_ts", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_ts", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
