package com.soch.Integra.entities;
// default package
// Generated Dec 21, 2017 11:04:44 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssessmentTblAudit generated by hbm2java
 */
@Entity
@Table(name = "assessment_tbl_audit")
public class AssessmentAuditEntity implements java.io.Serializable {

	private Integer assessmentTblAuditId;
	private String operation;
	private Date processDate;
	private Integer assessmentId;
	private String name;
	private Date assessmentDt;
	private Date nextAssessmentDt;
	private String status;
	private Integer applicationId;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;

	public AssessmentAuditEntity() {
	}

	public AssessmentAuditEntity(String operation, Date processDate, Integer assessmentId, String name, Date assessmentDt,
			Date nextAssessmentDt, String status, Integer applicationId, String createdBy, Date createdTs,
			String updatedBy, Date updatedTs) {
		this.operation = operation;
		this.processDate = processDate;
		this.assessmentId = assessmentId;
		this.name = name;
		this.assessmentDt = assessmentDt;
		this.nextAssessmentDt = nextAssessmentDt;
		this.status = status;
		this.applicationId = applicationId;
		this.createdBy = createdBy;
		this.createdTs = createdTs;
		this.updatedBy = updatedBy;
		this.updatedTs = updatedTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "assessment_tbl_audit_id", unique = true, nullable = false)
	public Integer getAssessmentTblAuditId() {
		return this.assessmentTblAuditId;
	}

	public void setAssessmentTblAuditId(Integer assessmentTblAuditId) {
		this.assessmentTblAuditId = assessmentTblAuditId;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "process_date", length = 19)
	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	@Column(name = "ASSESSMENT_ID")
	public Integer getAssessmentId() {
		return this.assessmentId;
	}

	public void setAssessmentId(Integer assessmentId) {
		this.assessmentId = assessmentId;
	}

	@Column(name = "NAME", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ASSESSMENT_DT", length = 19)
	public Date getAssessmentDt() {
		return this.assessmentDt;
	}

	public void setAssessmentDt(Date assessmentDt) {
		this.assessmentDt = assessmentDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEXT_ASSESSMENT_DT", length = 19)
	public Date getNextAssessmentDt() {
		return this.nextAssessmentDt;
	}

	public void setNextAssessmentDt(Date nextAssessmentDt) {
		this.nextAssessmentDt = nextAssessmentDt;
	}

	@Column(name = "STATUS", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "APPLICATION_ID")
	public Integer getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(Integer applicationId) {
		this.applicationId = applicationId;
	}

	@Column(name = "CREATED_BY", length = 300)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "UPDATED_BY", length = 300)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_TS", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

}
