package com.soch.Integra.entities;
// Generated Apr 25, 2017 12:37:56 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CostTbl generated by hbm2java
 */
@Entity
@Table(name = "cost_tbl")
public class CostEntity implements java.io.Serializable {

	private int costId;
	private ApplicationEntity applicationEntity;
	private String typeName;
	private double typeValue;
	private Date createdTs;
	private String createdBy;



	@Id

	@Column(name = "COST_ID", unique = true, nullable = false)
	public int getCostId() {
		return this.costId;
	}

	public void setCostId(int costId) {
		this.costId = costId;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "APPLICATION_ID")
	public ApplicationEntity getApplicationEntity() {
		return this.applicationEntity;
	}

	public void setApplicationEntity(ApplicationEntity applicationEntity) {
		this.applicationEntity = applicationEntity;
	}
	
	@Column(name = "CREATED_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	
	
	@Column(name = "TYPE_NUMBER")
	public String getTypeName() {
		return this.typeName;
	}

	
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "TYPE_VALUE", length = 45)
	public double getTypeValue() {
		return this.typeValue;
	}

	public void setTypeValue(Double typeValue) {
		this.typeValue = typeValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}
	


}
