package com.soch.Integra.entities;
// Generated Apr 25, 2017 12:37:56 PM by Hibernate Tools 4.3.4.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.annotation.Generated;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatabaseTbl generated by hbm2java
 */
@Entity
@Table(name = "database_tbl")
public class DatabaseEntity implements java.io.Serializable {

	

	private int databaseId;
	private UserEntity userEntity;
	private String hostName;
	private String platform;
	private String dbVersion;
	private String hardware;
	private String updateLevel;
	private String addressLength;
	private String clockFrequency;
	private String memorySize;
	private String localDiskSpace;
	private Integer cpuCount;
	private Integer physicalCpuCount;
	private Integer logicalCpuCount;
	private String ipAddress;
	private String dbServer;
	private String serverName;
	private String archiveLogMode;
	private String sizeGb;
	private String purpose;
	private String osVersion;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;
	private String systemTag;
	private Set<ApplicationDatabaseEntity> applicationDatabaseEntities = new HashSet<ApplicationDatabaseEntity>(0);
	private Date licenseStartDt;
	private Date licenseEndDt;
	private Date licenseRenewDt;
	private String vendorName;
	private String productName;
	private String operatingSystem;
	private String controlName;
	
	
	
	
	private Set<ServerContactEntity> serverContactEntities = new HashSet<ServerContactEntity>(0); 
	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DATABASE_ID", unique = true, nullable = false)
	public int getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(int databaseId) {
		this.databaseId = databaseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANAGED_BY")
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "HOST_NAME", length = 100)
	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	@Column(name = "PLATFORM", length = 100)
	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	@Column(name = "DB_VERSION", length = 45)
	public String getDbVersion() {
		return this.dbVersion;
	}

	public void setDbVersion(String dbVersion) {
		this.dbVersion = dbVersion;
	}

	@Column(name = "HARDWARE")
	public String getHardware() {
		return this.hardware;
	}

	public void setHardware(String hardware) {
		this.hardware = hardware;
	}

	@Column(name = "UPDATE_LEVEL")
	public String getUpdateLevel() {
		return this.updateLevel;
	}

	public void setUpdateLevel(String updateLevel) {
		this.updateLevel = updateLevel;
	}

	@Column(name = "ADDRESS_LENGTH")
	public String getAddressLength() {
		return this.addressLength;
	}

	public void setAddressLength(String addressLength) {
		this.addressLength = addressLength;
	}

	@Column(name = "CLOCK_FREQUENCY")
	public String getClockFrequency() {
		return this.clockFrequency;
	}

	public void setClockFrequency(String clockFrequency) {
		this.clockFrequency = clockFrequency;
	}

	@Column(name = "MEMORY_SIZE")
	public String getMemorySize() {
		return this.memorySize;
	}

	public void setMemorySize(String memorySize) {
		this.memorySize = memorySize;
	}

	@Column(name = "LOCAL_DISK_SPACE")
	public String getLocalDiskSpace() {
		return this.localDiskSpace;
	}

	public void setLocalDiskSpace(String localDiskSpace) {
		this.localDiskSpace = localDiskSpace;
	}

	@Column(name = "CPU_COUNT")
	public Integer getCpuCount() {
		return this.cpuCount;
	}

	public void setCpuCount(Integer cpuCount) {
		this.cpuCount = cpuCount;
	}

	@Column(name = "PHYSICAL_CPU_COUNT")
	public Integer getPhysicalCpuCount() {
		return this.physicalCpuCount;
	}

	public void setPhysicalCpuCount(Integer physicalCpuCount) {
		this.physicalCpuCount = physicalCpuCount;
	}

	@Column(name = "LOGICAL_CPU_COUNT")
	public Integer getLogicalCpuCount() {
		return this.logicalCpuCount;
	}

	public void setLogicalCpuCount(Integer logicalCpuCount) {
		this.logicalCpuCount = logicalCpuCount;
	}

	@Column(name = "IP_ADDRESS", length = 45)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "DB_SERVER", length = 100)
	public String getDbServer() {
		return this.dbServer;
	}

	public void setDbServer(String dbServer) {
		this.dbServer = dbServer;
	}

	@Column(name = "SERVER_NAME", length = 100)
	public String getServerName() {
		return this.serverName;
	}

	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	@Column(name = "ARCHIVE_LOG_MODE", length = 100)
	public String getArchiveLogMode() {
		return this.archiveLogMode;
	}

	public void setArchiveLogMode(String archiveLogMode) {
		this.archiveLogMode = archiveLogMode;
	}

	@Column(name = "SIZE_GB", length = 10)
	public String getSizeGb() {
		return this.sizeGb;
	}

	public void setSizeGb(String sizeGb) {
		this.sizeGb = sizeGb;
	}

	@Column(name = "PURPOSE")
	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "databaseEntity")
	public Set<ApplicationDatabaseEntity> getapplicationDatabaseEntities() {
		return this.applicationDatabaseEntities;
	}

	public void setapplicationDatabaseEntities(Set<ApplicationDatabaseEntity> applicationDatabaseEntities) {
		this.applicationDatabaseEntities = applicationDatabaseEntities;
	}*/
	
	@Column(name = "OS_VERSION")
	public String getOsVersion() {
		return osVersion;
	}

	public void setOsVersion(String osVersion) {
		this.osVersion = osVersion;
	}
	
	@Column(name = "created_by", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_ts", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "updated_by", length = 100)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_ts", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}
	
	@Column(name = "system_tag")
	public String getSystemTag() {
		return systemTag;
	}

	public void setSystemTag(String systemTag) {
		this.systemTag = systemTag;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LICENSE_START_DT", length = 19)
	public Date getLicenseStartDt() {
		return this.licenseStartDt;
	}

	public void setLicenseStartDt(Date licenseStartDt) {
		this.licenseStartDt = licenseStartDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LICENSE_END_DT", length = 19)
	public Date getLicenseEndDt() {
		return this.licenseEndDt;
	}

	public void setLicenseEndDt(Date licenseEndDt) {
		this.licenseEndDt = licenseEndDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LICENSE_RENEW_DT", length = 19)
	public Date getLicenseRenewDt() {
		return this.licenseRenewDt;
	}

	public void setLicenseRenewDt(Date licenseRenewDt) {
		this.licenseRenewDt = licenseRenewDt;
	}

	@Column(name = "VENDOR_NAME", length = 500)
	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	@Column(name = "PRODUCT_NAME", length = 500)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}
	
	@Column(name = "OPERATING_SYSTEM", length = 500)
	public String getOperatingSystem() {
		return operatingSystem;
	}

	public void setOperatingSystem(String operatingSystem) {
		this.operatingSystem = operatingSystem;
	}
	
	@Column(name = "CONTROL_NAME", length = 500)
	public String getControlName() {
		return controlName;
	}

	public void setControlName(String controlName) {
		this.controlName = controlName;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "databaseEntity",cascade=CascadeType.ALL)
	public Set<ServerContactEntity> getServerContactEntities() {
		return serverContactEntities;
	}

	public void setServerContactEntities(Set<ServerContactEntity> serverContactEntities) {
		this.serverContactEntities = serverContactEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "databaseEntity",cascade=CascadeType.ALL)
	public Set<ApplicationDatabaseEntity> getApplicationDatabaseEntities() {
		return applicationDatabaseEntities;
	}

	public void setApplicationDatabaseEntities(Set<ApplicationDatabaseEntity> applicationDatabaseEntities) {
		this.applicationDatabaseEntities = applicationDatabaseEntities;
	}
	
	
	
}
