package com.soch.Integra.entities;
// Generated Apr 25, 2017 12:37:56 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DivisionTblId generated by hbm2java
 */
@Embeddable
public class DivisionEntityId implements java.io.Serializable {

	private int divisionId;
	private int officeTblOfficeId;

	public DivisionEntityId() {
	}

	public DivisionEntityId(int divisionId, int officeTblOfficeId) {
		this.divisionId = divisionId;
		this.officeTblOfficeId = officeTblOfficeId;
	}

	@Column(name = "DIVISION_ID", nullable = false)
	public int getDivisionId() {
		return this.divisionId;
	}

	public void setDivisionId(int divisionId) {
		this.divisionId = divisionId;
	}

	@Column(name = "OFFICE_TBL_OFFICE_ID", nullable = false)
	public int getOfficeTblOfficeId() {
		return this.officeTblOfficeId;
	}

	public void setOfficeTblOfficeId(int officeTblOfficeId) {
		this.officeTblOfficeId = officeTblOfficeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DivisionEntityId))
			return false;
		DivisionEntityId castOther = (DivisionEntityId) other;

		return (this.getDivisionId() == castOther.getDivisionId())
				&& (this.getOfficeTblOfficeId() == castOther.getOfficeTblOfficeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDivisionId();
		result = 37 * result + this.getOfficeTblOfficeId();
		return result;
	}

}
