package com.soch.Integra.entities;
// default package
// Generated Apr 20, 2017 1:33:06 PM by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * DivisionEntity generated by hbm2java
 */
@Entity
@Table(name = "division_tbl")
public class DivisionEntity implements java.io.Serializable {

	private int id;
	private String divisionName;
	private Set<ApplicationEntity> applicationEntities = new HashSet<ApplicationEntity>(0);
	//private OfficeEntity officeEntity;
	
	private Set<OfficeEntity> officeEntities = new HashSet<OfficeEntity>(0);
	
	
	@Id
	@Column(name="DIVISION_ID")
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "DIVISION_NAME")
	public String getDivisionName() {
		return this.divisionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "divisionEntity")
	public Set<ApplicationEntity> getApplicationEntities() {
		return applicationEntities;
	}

	public void setApplicationEntities(Set<ApplicationEntity> applicationEntities) {
		this.applicationEntities = applicationEntities;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "divisionEntity")
	public Set<OfficeEntity> getOfficeEntities() {
		return officeEntities;
	}

	public void setOfficeEntities(Set<OfficeEntity> officeEntities) {
		this.officeEntities = officeEntities;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OFFICE_TBL_OFFICE_ID", nullable = false, insertable = false, updatable = false)
	public OfficeEntity getOfficeEntity() {
		return officeEntity;
	}

	public void setOfficeEntity(OfficeEntity officeEntity) {
		this.officeEntity = officeEntity;
	}*/

	public void setDivisionName(String divisionName) {
		this.divisionName = divisionName;
	}
	
	

}
