package com.soch.Integra.entities;
// Generated Apr 25, 2017 12:37:56 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FiscalYearInfoTbl generated by hbm2java
 */
@Entity
@Table(name = "fiscal_year_info_tbl")
public class FiscalYearInfoEntity implements java.io.Serializable {

	private int fyId;
	private ApplicationEntity applicationEntity;
	private UserEntity userEntity;
	private Integer fyNumber;
	private String fyContent;
	private String fyMoaTerm;
	private Date createdTs;
	private boolean activityFlag;

	public FiscalYearInfoEntity() {
	}

	public FiscalYearInfoEntity(int fyId) {
		this.fyId = fyId;
	}

	public FiscalYearInfoEntity(int fyId, ApplicationEntity applicationEntity, UserEntity userEntity, Integer fyNumber,
			String fyContent, String fyMoaTerm, Date createdTs) {
		this.fyId = fyId;
		this.applicationEntity = applicationEntity;
		this.userEntity = userEntity;
		this.fyNumber = fyNumber;
		this.fyContent = fyContent;
		this.fyMoaTerm = fyMoaTerm;
		this.createdTs = createdTs;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "FY_ID", unique = true, nullable = false)
	public int getFyId() {
		return this.fyId;
	}

	public void setFyId(int fyId) {
		this.fyId = fyId;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "APPLICATION_ID")
	public ApplicationEntity getApplicationEntity() {
		return this.applicationEntity;
	}

	public void setApplicationEntity(ApplicationEntity applicationEntity) {
		this.applicationEntity = applicationEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "FY_NUMBER")
	public Integer getFyNumber() {
		return this.fyNumber;
	}

	public void setFyNumber(Integer fyNumber) {
		this.fyNumber = fyNumber;
	}

	@Column(name = "FY_CONTENT", length = 45)
	public String getFyContent() {
		return this.fyContent;
	}

	public void setFyContent(String fyContent) {
		this.fyContent = fyContent;
	}

	@Column(name = "FY_MOA_TERM", length = 45)
	public String getFyMoaTerm() {
		return this.fyMoaTerm;
	}

	public void setFyMoaTerm(String fyMoaTerm) {
		this.fyMoaTerm = fyMoaTerm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "ACTIVITY_FLAG")
	public boolean isActivityFlag() {
		return activityFlag;
	}

	public void setActivityFlag(boolean activityFlag) {
		this.activityFlag = activityFlag;
	}
	
	

}
