package com.soch.Integra.entities;
// Generated Apr 25, 2017 12:37:56 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MoaTbl generated by hbm2java
 */
@Entity
@Table(name = "moa_tbl")
public class MoaEntity implements java.io.Serializable {

	private int moaId;
	private ApplicationEntity applicationEntity;
	private byte[] moa;
	private String moaName;
	private Date moaSignedDate;
	private Date createdTs;
	private String createdBy;

	public MoaEntity() {
	}

	public MoaEntity(int moaId) {
		this.moaId = moaId;
	}

	public MoaEntity(int moaId, ApplicationEntity applicationEntity, String createdBy, byte[] moa, String moaName,
			Date moaSignedDate, Date createdTs) {
		this.moaId = moaId;
		this.applicationEntity = applicationEntity;
		this.createdBy = createdBy;
		this.moa = moa;
		this.moaName = moaName;
		this.moaSignedDate = moaSignedDate;
		this.createdTs = createdTs;
	}

	@Id

	@Column(name = "MOA_ID", unique = true, nullable = false)
	public int getMoaId() {
		return this.moaId;
	}

	public void setMoaId(int moaId) {
		this.moaId = moaId;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "APPLICATION_ID")
	public ApplicationEntity getApplicationEntity() {
		return this.applicationEntity;
	}

	public void setApplicationEntity(ApplicationEntity applicationEntity) {
		this.applicationEntity = applicationEntity;
	}
	
	@Column(name = "CREATED_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "MOA")
	public byte[] getMoa() {
		return this.moa;
	}

	public void setMoa(byte[] moa) {
		this.moa = moa;
	}

	@Column(name = "MOA_NAME", length = 100)
	public String getMoaName() {
		return this.moaName;
	}

	public void setMoaName(String moaName) {
		this.moaName = moaName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MOA_SIGNED_DATE", length = 19)
	public Date getMoaSignedDate() {
		return this.moaSignedDate;
	}

	public void setMoaSignedDate(Date moaSignedDate) {
		this.moaSignedDate = moaSignedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

}
