package com.soch.Integra.entities;
// Generated Apr 10, 2018 1:21:46 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.engine.internal.Cascade;

/**
 * MouTbl generated by hbm2java
 */
@Entity
@Table(name = "mou_tbl")
public class MOUEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int mouId;
	private ApplicationEntity applicationEntity;
	private String name;
	private boolean signed;
	private Date recertificationDt;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;
	private Set<MOUDocEntity> mouDocEntities = new HashSet<MOUDocEntity>(0);
	private Date receiptDt;
	

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "MOU_ID", nullable = false)
	public int getMouId() {
		return this.mouId;
	}

	public void setMouId(int mouId) {
		this.mouId = mouId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPLICATION_ID")
	public ApplicationEntity getApplicationEntity() {
		return applicationEntity;
	}

	public void setApplicationEntity(ApplicationEntity applicationEntity) {
		this.applicationEntity = applicationEntity;
	}

	@Column(name = "NAME", length = 1000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SIGNED", length = 1)
	public boolean getSigned() {
		return this.signed;
	}

	public void setSigned(boolean signed) {
		this.signed = signed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECERTIFICATION_DT", length = 19)
	public Date getRecertificationDt() {
		return this.recertificationDt;
	}

	public void setRecertificationDt(Date recertificationDt) {
		this.recertificationDt = recertificationDt;
	}

	@Column(name = "CREATED_BY", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "UPDATED_BY", length = 100)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_TS", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mouEntity",cascade=CascadeType.ALL)
	public Set<MOUDocEntity> getMouDocEntities() {
		return mouDocEntities;
	}

	public void setMouDocEntities(Set<MOUDocEntity> mouDocEntities) {
		this.mouDocEntities = mouDocEntities;
	}

	@Column(name = "RECEIPT_DT")
	public Date getReceiptDt() {
		return receiptDt;
	}

	public void setReceiptDt(Date receiptDt) {
		this.receiptDt = receiptDt;
	}

	
	
	

}
