package com.soch.Integra.entities;
// default package
// Generated Apr 20, 2017 1:33:06 PM by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * OfficeTbl generated by hbm2java
 */
@Entity
@Table(name = "office_tbl")
public class OfficeEntity implements java.io.Serializable {

	private int officeId;
	private String acronym;
	private String description;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String zipCode;
	private String phoneNumber;
	//private Set<DivisionEntity> divisionEntities = new HashSet<DivisionEntity>(0);
	private SubsidaryEntity subsidaryEntity;
	private Set<ApplicationEntity> applicationEntities;
	private DivisionEntity divisionEntity;

	

	@Id
	@Column(name = "OFFICE_ID", nullable = false)
	public int getOfficeId() {
		return officeId;
	}

	public void setOfficeId(int officeId) {
		this.officeId = officeId;
	}


	@Column(name = "ACRONYM")
	public String getAcronym() {
		return this.acronym;
	}

	public void setAcronym(String acronym) {
		this.acronym = acronym;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ADDRESS_LINE1", length = 100)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE2", length = 100)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "CITY", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIP_CODE", length = 20)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "PHONE_NUMBER", length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	
	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "officeEntity")
	public Set<DivisionEntity> getDivisionEntities() {
		return divisionEntities;
	}

	public void setDivisionEntities(Set<DivisionEntity> divisionEntities) {
		this.divisionEntities = divisionEntities;
	}*/
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSIDARY_TBL_SUBSIDARY_ID", nullable = false, insertable = false, updatable = false)
	public SubsidaryEntity getSubsidaryEntity() {
		return subsidaryEntity;
	}

	public void setSubsidaryEntity(SubsidaryEntity subsidaryEntity) {
		this.subsidaryEntity = subsidaryEntity;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIVISION_ID", nullable = false, insertable = false, updatable = false)
	public DivisionEntity getDivisionEntity() {
		return divisionEntity;
	}

	public void setDivisionEntity(DivisionEntity divisionEntity) {
		this.divisionEntity = divisionEntity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "officeEntity",cascade=CascadeType.ALL)
	public Set<ApplicationEntity> getApplicationEntities() {
		return applicationEntities;
	}

	public void setApplicationEntities(Set<ApplicationEntity> applicationEntities) {
		this.applicationEntities = applicationEntities;
	}
	
	
	
	
	
	

}
