package com.soch.Integra.entities;
// Generated Apr 25, 2017 12:37:56 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OfficeTblId generated by hbm2java
 */
@Embeddable
public class OfficeEntityId implements java.io.Serializable {

	private int officeId;
	private int subsidaryTblSubsidaryId;

	public OfficeEntityId() {
	}

	public OfficeEntityId(int officeId, int subsidaryTblSubsidaryId) {
		this.officeId = officeId;
		this.subsidaryTblSubsidaryId = subsidaryTblSubsidaryId;
	}

	@Column(name = "OFFICE_ID", nullable = false)
	public int getOfficeId() {
		return this.officeId;
	}

	public void setOfficeId(int officeId) {
		this.officeId = officeId;
	}

	@Column(name = "SUBSIDARY_TBL_SUBSIDARY_ID", nullable = false)
	public int getSubsidaryTblSubsidaryId() {
		return this.subsidaryTblSubsidaryId;
	}

	public void setSubsidaryTblSubsidaryId(int subsidaryTblSubsidaryId) {
		this.subsidaryTblSubsidaryId = subsidaryTblSubsidaryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OfficeEntityId))
			return false;
		OfficeEntityId castOther = (OfficeEntityId) other;

		return (this.getOfficeId() == castOther.getOfficeId())
				&& (this.getSubsidaryTblSubsidaryId() == castOther.getSubsidaryTblSubsidaryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOfficeId();
		result = 37 * result + this.getSubsidaryTblSubsidaryId();
		return result;
	}

}
