package com.soch.Integra.entities;
// default package
// Generated Oct 23, 2017 2:17:10 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;

/**
 * PolicyReviewTbl generated by hbm2java
 */
@Entity
@Table(name = "policy_review_tbl")
public class PolicyReviewEntity implements java.io.Serializable {

	private Integer policyReview;
	private PolicyGrpEntity policyGrpEntity;
	private String assignedTo;
	private String comments;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;
	private String status;

	private Date dueDate;
	
    private Set<PolicyReviewerCommentsEntity> policyReviewerCommentsEntities;	
    private Set<PolicyReviewSessionEntity> PolicyReviewSessionEntity;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "POLICY_REVIEW_ID", unique = true, nullable = false)
	public Integer getPolicyReview() {
		return this.policyReview;
	}

	public void setPolicyReview(Integer policyReview) {
		this.policyReview = policyReview;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POLICY_GRP_ID", nullable = false)
	public PolicyGrpEntity getPolicyGrpEntity() {
		return policyGrpEntity;
	}

	public void setPolicyGrpEntity(PolicyGrpEntity policyGrpEntity) {
		this.policyGrpEntity = policyGrpEntity;
	}


	@Column(name = "ASSIGNED_TO", length = 500)
	public String getAssignedTo() {
		return this.assignedTo;
	}

	
	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

	@Column(name = "COMMENTS", length = 65535)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "CREATED_BY", length = 500)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "UPDATED_BY", length = 500)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_TS", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DUE_DATE", length = 19)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyReviewEntity", cascade=CascadeType.ALL)
	public Set<PolicyReviewerCommentsEntity> getPolicyReviewerCommentsEntities() {
		return policyReviewerCommentsEntities;
	}

	public void setPolicyReviewerCommentsEntities(Set<PolicyReviewerCommentsEntity> policyReviewerCommentsEntities) {
		this.policyReviewerCommentsEntities = policyReviewerCommentsEntities;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyReviewEntity", cascade=CascadeType.ALL)
	public Set<PolicyReviewSessionEntity> getPolicyReviewSessionEntity() {
		return PolicyReviewSessionEntity;
	}

	public void setPolicyReviewSessionEntity(Set<PolicyReviewSessionEntity> policyReviewSessionEntity) {
		PolicyReviewSessionEntity = policyReviewSessionEntity;
	}
	
	
	

}
