package com.soch.Integra.entities;
// default package
// Generated Nov 22, 2017 12:24:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PolicyLinkTbl generated by hbm2java
 */
@Entity
@Table(name = "policy_link_tbl")
public class PolicyLinkEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -149754065450815458L;
	private Integer policyLinkId;
    private PolicyEntity policyEntityByPolicyId;
    private PolicyEntity policyEntityByLinkPolicyId;
    private String linkText;
    private String createdBy;
    private Date createdTs;
    private String updatedBy;
    private Date updatedTs;
    private boolean activeFlag;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "policy_link_id", unique = true, nullable = false)
	public Integer getPolicyLinkId() {
		return this.policyLinkId;
	}

	public void setPolicyLinkId(Integer policyLinkId) {
		this.policyLinkId = policyLinkId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "policy_id")
	public PolicyEntity getPolicyEntityByPolicyId() {
		return policyEntityByPolicyId;
	}

	public void setPolicyEntityByPolicyId(PolicyEntity policyEntityByPolicyId) {
		this.policyEntityByPolicyId = policyEntityByPolicyId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "link_policy_id")
	public PolicyEntity getPolicyEntityByLinkPolicyId() {
		return policyEntityByLinkPolicyId;
	}

	public void setPolicyEntityByLinkPolicyId(PolicyEntity policyEntityByLinkPolicyId) {
		this.policyEntityByLinkPolicyId = policyEntityByLinkPolicyId;
	}

	@Column(name = "link_text", length = 65535)
	public String getLinkText() {
		return this.linkText;
	}

	public void setLinkText(String linkText) {
		this.linkText = linkText;
	}

	@Column(name = "created_by", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_ts", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "updated_by", length = 100)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_ts", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

	@Column(name = "active_flag", length = 1)
	public boolean getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

}
