package com.soch.Integra.entities;
// default package
// Generated Sep 13, 2017 3:01:37 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.engine.spi.CascadeStyle;

/**
 * PolicyTbl generated by hbm2java
 */
@Entity
@Table(name = "policy_tbl")
public class PolicyEntity implements java.io.Serializable {

	

	/**
	 * 
	 */
	private static final long serialVersionUID = -6065176346262728174L;
	private Integer policyId;
	private PolicyGrpEntity policyGrpEntity;
	private String controlNumber;
	private String policyName;
	private String description;
	private String policyVal;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;
	private String priority;
	private String procedures;
	private String guidelines;
	private String familyName;
	private String classType;
	private String assignedTo;
	private String assignedBy;
	private Date startDate;
	private Date endDate;
	private boolean status;
	private String isDesignDocument;
	private String configBaseline;
	private String auditRecords;
	private String artifacts;
	private String nonCov;
	private String securityPlan;
	private String isConfigSettings;
	private String linkString;
	private Set<PolicyReviewerCommentsEntity> policyReviewerCommentsEntities;
	private Set<PolicyDocumentsEntity> policyDocumentsEntities = new HashSet<PolicyDocumentsEntity>(0);
	private Set<PolicyLinkEntity> policyLinkEntitysForPolicyId = new HashSet<PolicyLinkEntity>(0);
	private Set<PolicyLinkEntity> policyLinkEntityForLinkPolicyId = new HashSet<PolicyLinkEntity>(0);
	private Set<AssessmentPolicyEntity> assessmentPolicyEntities = new HashSet<AssessmentPolicyEntity>(0);
	private List<SubPolicyEntity> subPolicyEntities = new ArrayList<SubPolicyEntity>(0);
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "policy_id", unique = true, nullable = false)
	public Integer getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "policy_grp_id")
	public PolicyGrpEntity getPolicyGrpEntity() {
		return policyGrpEntity;
	}

	public void setPolicyGrpEntity(PolicyGrpEntity policyGrpEntity) {
		this.policyGrpEntity = policyGrpEntity;
	}

	@Column(name = "control_number", length = 50)
	public String getControlNumber() {
		return this.controlNumber;
	}

	public void setControlNumber(String controlNumber) {
		this.controlNumber = controlNumber;
	}

	@Column(name = "policy_name", length = 100)
	public String getPolicyName() {
		return this.policyName;
	}

	public void setPolicyName(String policyName) {
		this.policyName = policyName;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "policy_val", length = 100)
	public String getPolicyVal() {
		return this.policyVal;
	}

	public void setPolicyVal(String policyVal) {
		this.policyVal = policyVal;
	}

	@Column(name = "created_by", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_ts", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "updated_by", length = 100)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_ts", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}
	
	@Column(name = "priority", length = 19)
	public String getPriority() {
		return priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}
	
	@Column(name = "procudures", length = 19)
	public String getProcedures() {
		return procedures;
	}

	public void setProcedures(String procedures) {
		this.procedures = procedures;
	}
	
	@Column(name = "guidelines", length = 19)
	public String getGuidelines() {
		return guidelines;
	}

	public void setGuidelines(String guidelines) {
		this.guidelines = guidelines;
	}
	
	@Column(name = "family_name", length = 19)
	public String getFamilyName() {
		return familyName;
	}

	public void setFamilyName(String familyName) {
		this.familyName = familyName;
	}
	
	@Column(name = "family_type", length = 19)
	public String getClassType() {
		return classType;
	}

	public void setClassType(String classType) {
		this.classType = classType;
	}
	
	@Column(name = "assigned_to", length = 19)
	public String getAssignedTo() {
		return assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}
	
	@Column(name = "assigned_by", length = 19)
	public String getAssignedBy() {
		return assignedBy;
	}

	public void setAssignedBy(String assignedBy) {
		this.assignedBy = assignedBy;
	}
	
	@Column(name = "start_dt", length = 19)
	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	
	@Column(name = "end_dt", length = 19)
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	
	@Column(name = "status", length = 19)
	public boolean getStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyEntity")
	public Set<PolicyReviewerCommentsEntity> getPolicyReviewerCommentsEntities() {
		return policyReviewerCommentsEntities;
	}

	public void setPolicyReviewerCommentsEntities(Set<PolicyReviewerCommentsEntity> policyReviewerCommentsEntities) {
		this.policyReviewerCommentsEntities = policyReviewerCommentsEntities;
	}
	
	@Column(name = "IS_DESIGN_DOCUMENT", length = 45)
	public String getIsDesignDocument() {
		return this.isDesignDocument;
	}

	public void setIsDesignDocument(String isDesignDocument) {
		this.isDesignDocument = isDesignDocument;
	}

	@Column(name = "CONFIG_BASELINE", length = 45)
	public String getConfigBaseline() {
		return this.configBaseline;
	}

	public void setConfigBaseline(String configBaseline) {
		this.configBaseline = configBaseline;
	}

	@Column(name = "AUDIT_RECORDS", length = 45)
	public String getAuditRecords() {
		return this.auditRecords;
	}

	public void setAuditRecords(String auditRecords) {
		this.auditRecords = auditRecords;
	}

	@Column(name = "ARTIFACTS", length = 65535)
	public String getArtifacts() {
		return this.artifacts;
	}

	public void setArtifacts(String artifacts) {
		this.artifacts = artifacts;
	}

	@Column(name = "NON_COV", length = 65535)
	public String getNonCov() {
		return this.nonCov;
	}

	public void setNonCov(String nonCov) {
		this.nonCov = nonCov;
	}
	
	@Column(name = "SECURITY_PLAN", length = 45)
	public String getSecurityPlan() {
		return this.securityPlan;
	}

	public void setSecurityPlan(String securityPlan) {
		this.securityPlan = securityPlan;
	}

	@Column(name = "IS_CONFIG_SETTINGS", length = 200)
	public String getIsConfigSettings() {
		return this.isConfigSettings;
	}

	public void setIsConfigSettings(String isConfigSettings) {
		this.isConfigSettings = isConfigSettings;
	}
	
	
	@Column(name = "LINK_STRING")
	public String getLinkString() {
		return linkString;
	}

	public void setLinkString(String linkString) {
		this.linkString = linkString;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyEntity", cascade=CascadeType.ALL)
	public Set<PolicyDocumentsEntity> getPolicyDocumentsEntities() {
		return policyDocumentsEntities;
	}

	public void setPolicyDocumentsEntities(Set<PolicyDocumentsEntity> policyDocumentsEntities) {
		this.policyDocumentsEntities = policyDocumentsEntities;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyEntityByPolicyId", cascade=CascadeType.ALL)
	public Set<PolicyLinkEntity> getPolicyLinkEntitysForPolicyId() {
		return policyLinkEntitysForPolicyId;
	}

	public void setPolicyLinkEntitysForPolicyId(Set<PolicyLinkEntity> policyLinkEntitysForPolicyId) {
		this.policyLinkEntitysForPolicyId = policyLinkEntitysForPolicyId;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyEntityByLinkPolicyId")
	public Set<PolicyLinkEntity> getPolicyLinkEntityForLinkPolicyId() {
		return policyLinkEntityForLinkPolicyId;
	}

	public void setPolicyLinkEntityForLinkPolicyId(Set<PolicyLinkEntity> policyLinkEntityForLinkPolicyId) {
		this.policyLinkEntityForLinkPolicyId = policyLinkEntityForLinkPolicyId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyEntity", cascade=CascadeType.ALL)
	public Set<AssessmentPolicyEntity> getAssessmentPolicyEntities() {
		return assessmentPolicyEntities;
	}

	public void setAssessmentPolicyEntities(Set<AssessmentPolicyEntity> assessmentPolicyEntities) {
		this.assessmentPolicyEntities = assessmentPolicyEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policyEntity",cascade=CascadeType.ALL)
	public List<SubPolicyEntity> getSubPolicyEntities() {
		return subPolicyEntities;
	}

	public void setSubPolicyEntities(List<SubPolicyEntity> subPolicyEntities) {
		this.subPolicyEntities = subPolicyEntities;
	}
	
	
}
