package com.soch.Integra.entities;
// default package
// Generated Oct 24, 2017 12:26:50 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PolicyReviewerCommentsTbl generated by hbm2java
 */
@Entity
@Table(name = "policy_reviewer_comments_tbl")
public class PolicyReviewerCommentsEntity implements java.io.Serializable {

	private int policyReviewerCommentsId;
	private PolicyReviewEntity policyReviewEntity;
	private PolicyEntity policyEntity;
	private String comments;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "policy_reviewer_comments_id", unique = true, nullable = false)
	public int getPolicyReviewerCommentsId() {
		return this.policyReviewerCommentsId;
	}

	public void setPolicyReviewerCommentsId(int policyReviewerCommentsId) {
		this.policyReviewerCommentsId = policyReviewerCommentsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POLICY_REVIEW_ID")
	public PolicyReviewEntity getPolicyReviewEntity() {
		return policyReviewEntity;
	}

	public void setPolicyReviewEntity(PolicyReviewEntity policyReviewEntity) {
		this.policyReviewEntity = policyReviewEntity;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "policy_id")
	public PolicyEntity getPolicyEntity() {
		return policyEntity;
	}

	public void setPolicyEntity(PolicyEntity policyEntity) {
		this.policyEntity = policyEntity;
	}


	@Column(name = "comments", length = 65535)
	public String getComments() {
		return this.comments;
	}

	
	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "CREATED_BY", length = 500)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "UPDATED_BY", length = 500)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_TS", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

}
