package com.soch.Integra.entities;
// default package
// Generated Oct 24, 2017 1:47:37 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PolicyReviewSessionTbl generated by hbm2java
 */
@Entity
@Table(name = "policy_review_session_tbl")
public class PolicyReviewSessionEntity implements java.io.Serializable {

	private Integer policyReviewSessionId;
	private PolicyReviewEntity policyReviewEntity;
	private String token;
	private Date expiryTs;
	private boolean activeFlag;

	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "policy_review_session_id", unique = true, nullable = false)
	public Integer getPolicyReviewSessionId() {
		return this.policyReviewSessionId;
	}

	public void setPolicyReviewSessionId(Integer policyReviewSessionId) {
		this.policyReviewSessionId = policyReviewSessionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POLICY_REVIEW_ID")
	public PolicyReviewEntity getPolicyReviewEntity() {
		return policyReviewEntity;
	}

	public void setPolicyReviewEntity(PolicyReviewEntity policyReviewEntity) {
		this.policyReviewEntity = policyReviewEntity;
	}

	@Column(name = "token", length = 100)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiry_ts", length = 19)
	public Date getExpiryTs() {
		return this.expiryTs;
	}

	public void setExpiryTs(Date expiryTs) {
		this.expiryTs = expiryTs;
	}

	@Column(name = "ACTIVE_FLAG", length = 1)
	public boolean getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

}
