package com.soch.Integra.entities;
// Generated Jul 11, 2018 10:33:44 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PrecinctTypeTbl generated by hbm2java
 */
@Entity
@Table(name = "precinct_type_tbl")
public class PrecinctTypeEntity implements java.io.Serializable {

	private Integer precinctTypeId;
	private String typeName;
	private Set<SolutionsEntity> solutionsEntities = new HashSet<SolutionsEntity>(0);

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRECINCT_TYPE_ID", unique = true, nullable = false)
	public Integer getPrecinctTypeId() {
		return this.precinctTypeId;
	}

	public void setPrecinctTypeId(Integer precinctTypeId) {
		this.precinctTypeId = precinctTypeId;
	}

	@Column(name = "TYPE_NAME", length = 200)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "precinctTypeEntity")
	public Set<SolutionsEntity> getSolutionsEntities() {
		return solutionsEntities;
	}

	public void setSolutionsEntities(Set<SolutionsEntity> solutionsEntities) {
		this.solutionsEntities = solutionsEntities;
	}

	
	

}
