package com.soch.Integra.entities;
// Generated Apr 25, 2017 12:37:56 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServerTbl generated by hbm2java
 */
@Entity
@Table(name = "server_tbl")
public class ServerEntity implements java.io.Serializable {

	private int serverId;
	private String name;
	private String assetTag;
	private String systemType;
	private String equipmentType;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String zipCode;
	private Date licenseStartDt;
	private Date licenseEndDt;
	private Date licenseRenewDt;
	private String vendorName;
	private String productName;
	private Set<ApplicationServerEntity> applicationServerEntities = new HashSet<ApplicationServerEntity>(0);
	private Set<ServerContactEntity> serverContactEntities = new HashSet<ServerContactEntity>(0);
	
	public ServerEntity() {
	}

	public ServerEntity(int serverId) {
		this.serverId = serverId;
	}

	public ServerEntity(int serverId, String name, String assetTag, String systemType, String equipmentType,
			String addressLine1, String addressLine2, String city, String zipCode,
			Set<ApplicationServerEntity> applicationServerEntities) {
		this.serverId = serverId;
		this.name = name;
		this.assetTag = assetTag;
		this.systemType = systemType;
		this.equipmentType = equipmentType;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.zipCode = zipCode;
		this.applicationServerEntities = applicationServerEntities;
	}

	@Id

	@Column(name = "SERVER_ID", unique = true, nullable = false)
	public int getServerId() {
		return this.serverId;
	}

	public void setServerId(int serverId) {
		this.serverId = serverId;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ASSET_TAG", length = 45)
	public String getAssetTag() {
		return this.assetTag;
	}

	public void setAssetTag(String assetTag) {
		this.assetTag = assetTag;
	}

	@Column(name = "SYSTEM_TYPE", length = 45)
	public String getSystemType() {
		return this.systemType;
	}

	public void setSystemType(String systemType) {
		this.systemType = systemType;
	}

	@Column(name = "EQUIPMENT_TYPE", length = 45)
	public String getEquipmentType() {
		return this.equipmentType;
	}

	public void setEquipmentType(String equipmentType) {
		this.equipmentType = equipmentType;
	}

	@Column(name = "ADDRESS_LINE1", length = 100)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE2", length = 100)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "CITY", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ZIP_CODE", length = 20)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serverEntity")
	public Set<ApplicationServerEntity> getApplicationServerEntities() {
		return this.applicationServerEntities;
	}

	public void setApplicationServerEntities(Set<ApplicationServerEntity> applicationServerEntities) {
		this.applicationServerEntities = applicationServerEntities;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LICENSE_START_DT", length = 19)
	public Date getLicenseStartDt() {
		return this.licenseStartDt;
	}

	public void setLicenseStartDt(Date licenseStartDt) {
		this.licenseStartDt = licenseStartDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LICENSE_END_DT", length = 19)
	public Date getLicenseEndDt() {
		return this.licenseEndDt;
	}

	public void setLicenseEndDt(Date licenseEndDt) {
		this.licenseEndDt = licenseEndDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LICENSE_RENEW_DT", length = 19)
	public Date getLicenseRenewDt() {
		return this.licenseRenewDt;
	}

	public void setLicenseRenewDt(Date licenseRenewDt) {
		this.licenseRenewDt = licenseRenewDt;
	}

	@Column(name = "VENDOR_NAME", length = 500)
	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	@Column(name = "PRODUCT_NAME", length = 500)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serverEntity",cascade=CascadeType.ALL)
	public Set<ServerContactEntity> getServerContactEntities() {
		return serverContactEntities;
	}

	public void setServerContactEntities(Set<ServerContactEntity> serverContactEntities) {
		this.serverContactEntities = serverContactEntities;
	}

	
	


}
