package com.soch.Integra.entities;
// Generated Aug 11, 2018 12:21:44 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServerContactTbl generated by hbm2java
 */
@Entity
@Table(name = "SERVER_CONTACT_TBL")
public class ServerContactEntity implements java.io.Serializable {

	private Integer serverContactId;
	private ServerEntity serverEntity;
	private String firstName;
	private String lastName;
	private String emailId;
	private String phoneNumber;
	private Boolean isPrimary;
	private String divisionName;
	private String cost;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;
	private DatabaseEntity databaseEntity;
	
	public ServerContactEntity() {
	}

	public ServerContactEntity(ServerEntity serverEntity, String firstName, String lastName, String emailId, String phoneNumber,
			Boolean isPrimary, String divisionName, String cost, String createdBy, Date createdTs, String updatedBy,
			Date updatedTs) {
		this.serverEntity = serverEntity;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailId = emailId;
		this.phoneNumber = phoneNumber;
		this.isPrimary = isPrimary;
		this.divisionName = divisionName;
		this.cost = cost;
		this.createdBy = createdBy;
		this.createdTs = createdTs;
		this.updatedBy = updatedBy;
		this.updatedTs = updatedTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SERVER_CONTACT_ID", unique = true, nullable = false)
	public Integer getServerContactId() {
		return this.serverContactId;
	}

	public void setServerContactId(Integer serverContactId) {
		this.serverContactId = serverContactId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVER_ID")
	public ServerEntity getServerEntity() {
		return serverEntity;
	}

	public void setServerEntity(ServerEntity serverEntity) {
		this.serverEntity = serverEntity;
	}
	
	@Column(name = "FIRST_NAME", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL_ID", length = 200)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "PHONE_NUMBER", length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "IS_PRIMARY", length = 1)
	public Boolean getIsPrimary() {
		return this.isPrimary;
	}

	public void setIsPrimary(Boolean isPrimary) {
		this.isPrimary = isPrimary;
	}

	@Column(name = "DIVISION_NAME", length = 200)
	public String getDivisionName() {
		return this.divisionName;
	}

	public void setDivisionName(String divisionName) {
		this.divisionName = divisionName;
	}

	@Column(name = "COST", length = 100)
	public String getCost() {
		return this.cost;
	}

	public void setCost(String cost) {
		this.cost = cost;
	}

	@Column(name = "CREATED_BY", length = 200)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "UPDATED_BY", length = 500)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_TS", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DATABASE_ID")
	public DatabaseEntity getDatabaseEntity() {
		return databaseEntity;
	}

	public void setDatabaseEntity(DatabaseEntity databaseEntity) {
		this.databaseEntity = databaseEntity;
	}
	
	

}
