package com.soch.Integra.entities;
// Generated Apr 23, 2018 10:38:33 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SolutionTypeTbl generated by hbm2java
 */
@Entity
@Table(name = "solution_type_tbl")
public class SolutionTypeEntity implements java.io.Serializable {

	private Integer solutionTypeId;
	private String typeName;
	private Set<SolutionsEntity> solutionsEntities = new HashSet<SolutionsEntity>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SOLUTION_TYPE_ID", unique = true, nullable = false)
	public Integer getSolutionTypeId() {
		return this.solutionTypeId;
	}

	public void setSolutionTypeId(Integer solutionTypeId) {
		this.solutionTypeId = solutionTypeId;
	}
	
	
	@Column(name = "TYPE_NAME", length = 500)
	public String getTypeName() {
		return this.typeName;
	}
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solutionTypeEntity")
	public Set<SolutionsEntity> getSolutionsEntities() {
		return solutionsEntities;
	}
	
	
	public void setSolutionsEntities(Set<SolutionsEntity> solutionsEntities) {
		this.solutionsEntities = solutionsEntities;
	}

	

	
	
}
