package com.soch.Integra.entities;
// Generated Apr 26, 2017 2:58:34 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatusTbl generated by hbm2java
 */
@Entity
@Table(name = "status_tbl")
public class StatusEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1454602835523807831L;
	private int statusId;
	private String name;
	private Set<ApplicationEntity> applicationEntities = new HashSet<ApplicationEntity>(0);


	@Id

	@Column(name = "STATUS_ID", unique = true, nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusEntity")
	public Set<ApplicationEntity> getApplicationEntities() {
		return applicationEntities;
	}

	public void setApplicationEntities(Set<ApplicationEntity> applicationEntities) {
		this.applicationEntities = applicationEntities;
	}

}
