package com.soch.Integra.entities;
// Generated Apr 25, 2017 12:37:56 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SubsidaryTblId generated by hbm2java
 */
@Embeddable
public class SubsidaryEntityId implements java.io.Serializable {

	private int subsidaryId;
	private int corporationTblCorporationId;

	public SubsidaryEntityId() {
	}

	public SubsidaryEntityId(int subsidaryId, int corporationTblCorporationId) {
		this.subsidaryId = subsidaryId;
		this.corporationTblCorporationId = corporationTblCorporationId;
	}

	@Column(name = "SUBSIDARY_ID", nullable = false)
	public int getSubsidaryId() {
		return this.subsidaryId;
	}

	public void setSubsidaryId(int subsidaryId) {
		this.subsidaryId = subsidaryId;
	}

	@Column(name = "CORPORATION_TBL_CORPORATION_ID", nullable = false)
	public int getCorporationTblCorporationId() {
		return this.corporationTblCorporationId;
	}

	public void setCorporationTblCorporationId(int corporationTblCorporationId) {
		this.corporationTblCorporationId = corporationTblCorporationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubsidaryEntityId))
			return false;
		SubsidaryEntityId castOther = (SubsidaryEntityId) other;

		return (this.getSubsidaryId() == castOther.getSubsidaryId())
				&& (this.getCorporationTblCorporationId() == castOther.getCorporationTblCorporationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSubsidaryId();
		result = 37 * result + this.getCorporationTblCorporationId();
		return result;
	}

}
