package com.soch.Integra.entities;
// Generated Apr 25, 2017 12:37:56 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemSensitivityTbl generated by hbm2java
 */
@Entity
@Table(name = "system_sensitivity_tbl")
public class SystemSensitivityEntity implements java.io.Serializable {

	private int systemSensitivityId;
	private String systemSensitivityValue;
	private String description;
	private Date createdTs;
	private Set<ApplicationEntity> applicationEntities = new HashSet<ApplicationEntity>(0);

	public SystemSensitivityEntity() {
	}

	public SystemSensitivityEntity(int systemSensitivityId) {
		this.systemSensitivityId = systemSensitivityId;
	}

	public SystemSensitivityEntity(int systemSensitivityId, UserEntity userEntity, String systemSensitivityValue,
			String description, Date createdTs, Set<ApplicationEntity> applicationEntities) {
		this.systemSensitivityId = systemSensitivityId;
		this.systemSensitivityValue = systemSensitivityValue;
		this.description = description;
		this.createdTs = createdTs;
		this.applicationEntities = applicationEntities;
	}

	@Id

	@Column(name = "SYSTEM_SENSITIVITY_ID", unique = true, nullable = false)
	public int getSystemSensitivityId() {
		return this.systemSensitivityId;
	}

	public void setSystemSensitivityId(int systemSensitivityId) {
		this.systemSensitivityId = systemSensitivityId;
	}

	@Column(name = "SYSTEM_SENSITIVITY_VALUE", length = 100)
	public String getSystemSensitivityValue() {
		return this.systemSensitivityValue;
	}

	public void setSystemSensitivityValue(String systemSensitivityValue) {
		this.systemSensitivityValue = systemSensitivityValue;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemSensitivityEntity")
	public Set<ApplicationEntity> getApplicationEntities() {
		return this.applicationEntities;
	}

	public void setApplicationEntities(Set<ApplicationEntity> applicationEntities) {
		this.applicationEntities = applicationEntities;
	}

}
