package com.soch.Integra.entities;
// Generated Apr 27, 2017 12:09:36 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserAppRoleTbl generated by hbm2java
 */
@Entity
@Table(name = "user_app_role_tbl")
public class UserAppRoleEntity implements java.io.Serializable {

	private int appRoleId;
	private String name;
	private Set<UserEntity> userEntities = new HashSet<UserEntity>(0);

	@Id

	@Column(name = "APP_ROLE_ID", unique = true, nullable = false)
	public int getAppRoleId() {
		return this.appRoleId;
	}

	public void setAppRoleId(int appRoleId) {
		this.appRoleId = appRoleId;
	}

	@Column(name = "NAME", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userAppRoleEntity")
	public Set<UserEntity> getUserEntities() {
		return this.userEntities;
	}

	public void setUserEntities(Set<UserEntity> userEntities) {
		this.userEntities = userEntities;
	}

}
