package com.soch.Integra.entities;
// Generated Apr 20, 2018 1:01:13 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendorAddressTbl generated by hbm2java
 */
@Entity
@Table(name = "vendor_address_tbl")
public class VendorAddressEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6140115422197954356L;
	
	private Integer addressId;
	private VendorsEntity vendorsEntity;
	private String streetName;
	private String city;
	private String state;
	private String zipcode;
	private String createdBy;
	private Date createdTs;
	private String updatedBy;
	private Date updatedTs;

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ADDRESS_ID", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VENDOR_ID")
	public VendorsEntity getVendorsEntity() {
		return vendorsEntity;
	}

	public void setVendorsEntity(VendorsEntity vendorsEntity) {
		this.vendorsEntity = vendorsEntity;
	}


	@Column(name = "STREET_NAME", length = 1000)
	public String getStreetName() {
		return this.streetName;
	}

	
	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	@Column(name = "CITY", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIPCODE", length = 45)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "CREATED_BY", length = 500)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TS", length = 19)
	public Date getCreatedTs() {
		return this.createdTs;
	}

	public void setCreatedTs(Date createdTs) {
		this.createdTs = createdTs;
	}

	@Column(name = "UPDATED_BY", length = 500)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_TS", length = 19)
	public Date getUpdatedTs() {
		return this.updatedTs;
	}

	public void setUpdatedTs(Date updatedTs) {
		this.updatedTs = updatedTs;
	}

}
